"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {papers,type Paper,type ChoiceQuestion} from "./papers-v2";
import {generatedPapers,unitPlans} from "./unit-plans";

type Answers=Record<number,number|string>;
type SavedProgress={answers:Answers;essay:string;submitted:boolean;score:number};
type ProgressMap=Record<string,SavedProgress>;
const points=(id:number)=>id<=10?1:id<=15?2:id<=25?1:id<=30?2:1.5;
const progressKey=(p:Paper)=>`${p.unit??1}-${p.id}`;
const progressStorage="english-13124-progress-v1";

export default function Home(){
 const [unitOpen,setUnitOpen]=useState<number|null>(null),[paper,setPaper]=useState<Paper|null>(null),[answers,setAnswers]=useState<Answers>({}),[essay,setEssay]=useState(""),[submitted,setSubmitted]=useState(false),[progress,setProgress]=useState<ProgressMap>({});
 const set=(id:number,value:number|string)=>setAnswers(a=>({...a,[id]:value}));
 const choiceCorrect=(q:ChoiceQuestion)=>answers[q.id]===q.answer;
 const matchCorrect=(id:number,answer:number)=>answers[id]===answer;
 const textCorrect=(id:number,answer:string)=>String(answers[id]??"").trim().toLowerCase()===answer.toLowerCase();
 const objectiveScore=useMemo(()=>{if(!paper)return 0;let s=0;paper.judgment.questions.forEach(q=>{if(choiceCorrect(q))s+=1});paper.reading.questions.forEach(q=>{if(choiceCorrect(q))s+=2});paper.matching.paragraphAnswers.forEach((a,i)=>{if(matchCorrect(16+i,a))s+=1});paper.matching.sentenceAnswers.forEach((a,i)=>{if(matchCorrect(21+i,a))s+=1});paper.sentenceFill.answers.forEach((a,i)=>{if(matchCorrect(26+i,a))s+=2});paper.wordFill.answers.forEach((a,i)=>{if(matchCorrect(31+i,a))s+=1.5});paper.wordForm.answers.forEach((a,i)=>{if(textCorrect(41+i,a))s+=1.5});return s},[paper,answers]);
 useEffect(()=>{try{setProgress(JSON.parse(localStorage.getItem(progressStorage)||"{}"))}catch{}},[]);
 useEffect(()=>{if(!paper)return;const key=progressKey(paper);setProgress(current=>{const next={...current,[key]:{answers,essay,submitted,score:objectiveScore}};try{localStorage.setItem(progressStorage,JSON.stringify(next))}catch{}return next})},[paper,answers,essay,submitted,objectiveScore]);
 const start=(p:Paper)=>{const saved=progress[progressKey(p)];setPaper(p);setAnswers(saved?.answers??{});setEssay(saved?.essay??"");setSubmitted(saved?.submitted??false);scrollTo(0,0)};
 const restart=()=>{if(!paper)return;setAnswers({});setEssay("");setSubmitted(false);scrollTo(0,0)};
 const catalog=[{unit:1,title:"Foreign Language Learning",subtitle:"外语学习 · Text A & Text B",papers},...unitPlans.map(u=>({unit:u.unit,title:u.title,subtitle:`${u.textA} · ${u.textB}`,papers:generatedPapers.filter(p=>p.unit===u.unit)}))];
 if(!paper)return <main><header className="topbar"><span className="brand"><b className="brandMark">E</b>英语（专）在线题库</span><span className="courseCode">课程代码 13124</span></header><section className="library libraryCompact"><div className="sectionTitle"><div><p className="eyebrow">全国高等教育自学考试 · 学习目录</p><h2>选择单元</h2></div><span className="progressBadge">46 套试卷</span></div><div className="unitList">{catalog.map(u=><div className="unitGroup" key={u.unit}><button className="unitCard" onClick={()=>setUnitOpen(n=>n===u.unit?null:u.unit)}><span className="unitNumber">{String(u.unit).padStart(2,"0")}</span><span className="unitInfo"><strong>{u.title}</strong><span>{u.subtitle}</span></span><span className="paperCount">{u.papers.length} 套试卷</span><span className={`arrow ${unitOpen===u.unit?"open":""}`}>→</span></button>{unitOpen===u.unit&&<div className="paperPanel"><div className="panelHeading"><p>Unit {u.unit} · {u.title}</p><h2>选择一套完整试卷</h2></div><div className="paperGrid">{u.papers.map(p=>{const saved=progress[progressKey(p)];return <article className={`paperCard ${saved?.submitted?"completedPaper":""}`} key={`${u.unit}-${p.id}`}><div className="paperTop"><span>{String(p.id).padStart(2,"0")}</span><em>{saved?.submitted?"✓ 已完成":p.level}</em></div><h3>{p.title}</h3>{saved?.submitted?<p className="savedScore">客观题得分 <strong>{saved.score} / 70</strong></p>:<p>51题 · 150分钟 · 满分100分 · 交卷后查看答案解析</p>}<dl><div><dt>客观题</dt><dd>70分</dd></div><div><dt>写作</dt><dd>30分</dd></div></dl><button className="startButton" onClick={()=>start(p)}>{saved?.submitted?"查看结果":"开始答题"} <span>→</span></button></article>})}</div></div>}</div>)}</div></section></main>;
 const choice=(q:ChoiceQuestion)=><Question key={q.id} id={q.id} submitted={submitted} correct={choiceCorrect(q)} answer={q.options[q.answer]} explanation={q.explanation}><p>{q.id}. {q.prompt}</p><Options id={q.id} options={q.options} value={answers[q.id]} disabled={submitted} onChange={v=>set(q.id,v)}/></Question>;
 const match=(id:number,prompt:string,opts:string[],answer:number,explanation:string)=><Question key={id} id={id} submitted={submitted} correct={matchCorrect(id,answer)} answer={opts[answer]} explanation={explanation}><p>{id}. {prompt}</p><Options id={id} options={opts} value={answers[id]} disabled={submitted} onChange={v=>set(id,v)}/></Question>;
 return <main className="examShell"><header className="examHeader"><button onClick={()=>setPaper(null)}>← 返回 Unit {paper.unit??1}</button><div><strong>{paper.title}</strong><span>内容来源：Unit {paper.unit??1}{paper.unitTitle?` · ${paper.unitTitle}`:""}</span></div><span>150分钟 · 100分</span></header><div className="examLayout"><article className="examPaper"><DrawingLayer paperId={`${paper.unit??1}-${paper.id}`}/><div className="examContent"><div className="examIntro"><p>高等教育自学考试英语（专）模拟试题</p><h1>{paper.title}</h1><div><span>课程代码 13124</span><span>51题</span><span>满分100分</span></div></div>
 {paper.coverage&&<details className="coverageBox"><summary>查看本卷教材覆盖清单 · {paper.coverage.source}</summary><p><strong>课文内容：</strong>{paper.coverage.textFacts.join("；")}</p><p><strong>练习重点：</strong>{paper.coverage.exerciseFocus.join("；")}</p><p><strong>单词：</strong>{paper.coverage.vocabulary.join(" · ")}</p><p><strong>短语：</strong>{paper.coverage.phrases.join(" · ")}</p></details>}
 <Section title="第一部分：阅读判断（第1～10题，每题1分，共10分）" instruction="阅读短文，根据文章内容选择A（正确）、B（错误）或C（未提及）。" passageTitle={paper.judgment.title} passage={paper.judgment.passage}>{paper.judgment.questions.map(choice)}</Section>
 <Section title="第二部分：阅读选择（第11～15题，每题2分，共10分）" instruction="阅读短文，从每题所给的4个选项中选出最佳选项。" passageTitle={paper.reading.title} passage={paper.reading.passage}>{paper.reading.questions.map(choice)}</Section>
 <Section title="第三部分：概括段落大意和补全句子（第16～25题，每题1分，共10分）" instruction="Task 1：为第①～⑤段分别选择正确的段落大意；Task 2：根据短文内容补全句子。" passageTitle={paper.matching.title} passage={paper.matching.passage}><h3 className="taskTitle">Task 1</h3>{paper.matching.paragraphAnswers.map((a,i)=>match(16+i,paper.matching.paragraphPrompts?.[i]??`Paragraph ${i+1}`,paper.matching.paragraphOptions,a,paper.matching.explanations[i]))}<h3 className="taskTitle">Task 2</h3>{paper.matching.sentenceAnswers.map((a,i)=>match(21+i,paper.matching.sentencePrompts?.[i]??["A clear purpose helps learners ____.","Repeated contact helps learners ____.","Recording phrases in context helps learners ____.","Using language helps learners ____.","Weekly review helps learners ____."][i],paper.matching.sentenceOptions,a,paper.matching.explanations[5+i]))}</Section>
 <Section title="第四部分：填句补文（第26～30题，每题2分，共10分）" instruction="短文有5处空白，短文后有6个句子，其中5个取自短文，请将其分别放回原有位置。" passageTitle={paper.sentenceFill.title}><GapPassage parts={paper.sentenceFill.passageParts} start={26}/><div className="bank">{paper.sentenceFill.options.map((x,i)=><span key={x}>{String.fromCharCode(65+i)}. {x}</span>)}</div>{paper.sentenceFill.answers.map((a,i)=>match(26+i,`第 ${26+i} 空`,paper.sentenceFill.options,a,paper.sentenceFill.explanations[i]))}</Section>
 <Section title="第五部分：填词补文（第31～40题，每题1.5分，共15分）" instruction="短文有10处空白，短文后列出12个词，其中10个取自短文，请将其分别放回原有位置。" passageTitle={paper.wordFill.title}><GapPassage parts={paper.wordFill.passageParts} start={31}/><div className="bank words">{paper.wordFill.options.map((x,i)=><span key={x}>{String.fromCharCode(65+i)}. {x}</span>)}</div>{paper.wordFill.answers.map((a,i)=>match(31+i,`第 ${31+i} 空`,paper.wordFill.options,a,paper.wordFill.explanations[i]))}</Section>
 <Section title="第六部分：完形补文（第41～50题，每题1.5分，共15分）" instruction="短文有10处空白，每处空白后的括号内有一个词，请根据短文内容将其正确形式填入文中。" passageTitle={paper.wordForm.title}><FormPassage paper={paper}/>{paper.wordForm.answers.map((a,i)=><Question key={41+i} id={41+i} submitted={submitted} correct={textCorrect(41+i,a)} answer={a} explanation={paper.wordForm.explanations[i]}><label className="textAnswer">{41+i}. ({paper.wordForm.roots[i]})<input value={String(answers[41+i]??"")} disabled={submitted} onChange={e=>set(41+i,e.target.value)}/></label></Question>)}</Section>
 <Section title="第七部分：短文写作（第51题，30分）" instruction="根据所给任务完成一篇约80词的英文短文。"><div className="essayPrompt">{paper.essay.prompt}</div><textarea className="essayBox" value={essay} disabled={submitted} onChange={e=>setEssay(e.target.value)} placeholder="在这里输入英文作文……"/><p className="wordCount">约 {essay.trim()?essay.trim().split(/\s+/).length:0} 词</p>{submitted&&<div className="analysis"><strong>参考范文</strong><p>{paper.essay.sample}</p><strong>解析</strong><p>{paper.essay.analysis}</p></div>}</Section>
 {!submitted?<button className="submitExam" onClick={()=>{if(confirm(`已完成 ${Object.keys(answers).length}/50 道客观题，确定交卷吗？`)){setSubmitted(true);scrollTo(0,0)}}}>提交试卷</button>:<div className="resultCard"><em>✓ 已完成</em><p>客观题得分</p><strong>{objectiveScore} / 70</strong><span>作文按参考范文与评分提示自评（30分）</span><button onClick={restart}>重新做题（保留手写标记）</button></div>}
 </div></article><aside className="answerCard"><strong>答题卡</strong><div>{Array.from({length:50},(_,i)=><a key={i} href={`#q-${i+1}`} className={answers[i+1]!==undefined?"done":""}>{i+1}</a>)}</div><p>已答 {Object.keys(answers).length} / 50</p></aside></div></main>
}

function DrawingLayer({paperId}:{paperId:string}){
 const canvasRef=useRef<HTMLCanvasElement>(null),wrapRef=useRef<HTMLDivElement>(null),drawing=useRef(false),last=useRef({x:0,y:0});
 const [active,setActive]=useState(false),[eraser,setEraser]=useState(false),[hasInk,setHasInk]=useState(false);
 const inkKey=`english-13124-ink-${paperId}`;
 useEffect(()=>{const canvas=canvasRef.current,parent=canvas?.parentElement;if(!canvas||!parent)return;let first=true;const resize=()=>{const old=document.createElement("canvas");old.width=canvas.width;old.height=canvas.height;old.getContext("2d")?.drawImage(canvas,0,0);const dpr=Math.min(devicePixelRatio||1,2),w=parent.clientWidth,h=parent.scrollHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;const ctx=canvas.getContext("2d");ctx?.scale(dpr,dpr);if(old.width&&old.height)ctx?.drawImage(old,0,0,old.width,old.height,0,0,w,h);if(first){first=false;const saved=localStorage.getItem(inkKey);if(saved){const image=new Image();image.onload=()=>ctx?.drawImage(image,0,0,image.width,image.height,0,0,w,h);image.src=saved;setHasInk(true)}}};resize();const observer=new ResizeObserver(resize);observer.observe(parent);return()=>observer.disconnect()},[paperId,inkKey]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const down=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!active)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=point(e)};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;e.preventDefault();const canvas=canvasRef.current,ctx=canvas?.getContext("2d"),p=point(e);if(!ctx)return;ctx.beginPath();ctx.moveTo(last.current.x,last.current.y);ctx.lineTo(p.x,p.y);ctx.lineCap="round";ctx.lineJoin="round";ctx.lineWidth=eraser?22:2.4;ctx.globalCompositeOperation=eraser?"destination-out":"source-over";ctx.strokeStyle="#c7352b";ctx.stroke();last.current=p;setHasInk(true)};
 const saveInk=()=>{const c=canvasRef.current;if(!c)return;try{localStorage.setItem(inkKey,c.toDataURL("image/png"))}catch{}};
 const stop=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(drawing.current){drawing.current=false;saveInk()}e.currentTarget.releasePointerCapture?.(e.pointerId)};
 const clear=()=>{const c=canvasRef.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);try{localStorage.removeItem(inkKey)}catch{}setHasInk(false)};
 return <div ref={wrapRef} className="inkTools"><div className="inkToolbar" role="toolbar" aria-label="卷面手写工具"><button className={active&&!eraser?"selected":""} onClick={()=>{setActive(true);setEraser(false)}}>✎ 手写</button><button className={active&&eraser?"selected":""} onClick={()=>{setActive(true);setEraser(true)}}>橡皮擦</button><button onClick={()=>setActive(false)} disabled={!active}>完成</button><button onClick={clear} disabled={!hasInk}>清空</button></div><canvas ref={canvasRef} className={`inkCanvas ${active?"active":""}`} aria-label="卷面手写批注层" onPointerDown={down} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/>{active&&<div className="inkHint">手写模式已开启 · 用 Apple Pencil 在卷面批注，点“完成”继续答题</div>}</div>
}

function Section({title,instruction,passageTitle,passage,children}:{title:string;instruction:string;passageTitle?:string;passage?:string;children:React.ReactNode}){return <section className="questionSection"><h2>{title}</h2><p className="instruction">{instruction}</p>{passageTitle&&<h3 className="passageTitle">{passageTitle}</h3>}{passage&&<div className="passage">{passage.split("\n").map((p,i)=><p key={i}>{p}</p>)}</div>}{children}</section>}
function Options({id,options,value,disabled,onChange}:{id:number;options:string[];value:number|string|undefined;disabled:boolean;onChange:(v:number)=>void}){return <div className="options">{options.map((x,i)=><label key={x}><input type="radio" name={`q${id}`} checked={value===i} disabled={disabled} onChange={()=>onChange(i)}/><span>{x}</span></label>)}</div>}
function Question({id,submitted,correct,answer,explanation,children}:{id:number;submitted:boolean;correct:boolean;answer:string;explanation:string;children:React.ReactNode}){return <div id={`q-${id}`} className={`question ${submitted?(correct?"correct":"wrong"):""}`}>{children}{submitted&&<div className="analysis"><strong>{correct?"回答正确":`正确答案：${answer}`}</strong><p>{explanation}</p></div>}</div>}
function GapPassage({parts,start}:{parts:string[];start:number}){return <div className="passage gapPassage">{parts.map((p,i)=><span key={i}>{p}{i<parts.length-1&&<b>　{start+i}　</b>}</span>)}</div>}
function FormPassage({paper}:{paper:Paper}){return <div className="passage gapPassage">{paper.wordForm.passageParts.map((p,i)=><span key={i}>{p}{i<10&&<b>　{41+i}　({paper.wordForm.roots[i]})</b>}</span>)}</div>}
