"use client";
import {useMemo,useState} from "react";
import {papers,type Paper,type ChoiceQuestion} from "./papers-v2";

type Answers=Record<number,number|string>;
const points=(id:number)=>id<=10?1:id<=15?2:id<=25?1:id<=30?2:1.5;

export default function Home(){
 const [unitOpen,setUnitOpen]=useState(false),[paper,setPaper]=useState<Paper|null>(null),[answers,setAnswers]=useState<Answers>({}),[essay,setEssay]=useState(""),[submitted,setSubmitted]=useState(false);
 const set=(id:number,value:number|string)=>setAnswers(a=>({...a,[id]:value}));
 const choiceCorrect=(q:ChoiceQuestion)=>answers[q.id]===q.answer;
 const matchCorrect=(id:number,answer:number)=>answers[id]===answer;
 const textCorrect=(id:number,answer:string)=>String(answers[id]??"").trim().toLowerCase()===answer.toLowerCase();
 const objectiveScore=useMemo(()=>{if(!paper)return 0;let s=0;paper.judgment.questions.forEach(q=>{if(choiceCorrect(q))s+=1});paper.reading.questions.forEach(q=>{if(choiceCorrect(q))s+=2});paper.matching.paragraphAnswers.forEach((a,i)=>{if(matchCorrect(16+i,a))s+=1});paper.matching.sentenceAnswers.forEach((a,i)=>{if(matchCorrect(21+i,a))s+=1});paper.sentenceFill.answers.forEach((a,i)=>{if(matchCorrect(26+i,a))s+=2});paper.wordFill.answers.forEach((a,i)=>{if(matchCorrect(31+i,a))s+=1.5});paper.wordForm.answers.forEach((a,i)=>{if(textCorrect(41+i,a))s+=1.5});return s},[paper,answers]);
 const start=(p:Paper)=>{setPaper(p);setAnswers({});setEssay("");setSubmitted(false);scrollTo(0,0)};
 if(!paper)return <main><header className="topbar"><span className="brand"><b className="brandMark">E</b>英语（专）在线题库</span><span className="courseCode">课程代码 13124</span></header><section className="hero"><p className="eyebrow">全国高等教育自学考试</p><h1>按单元学习，<br/>按真题训练。</h1><p className="heroText">依据《英语（一）自学教程》Unit 1 编写，每套严格采用2024年10月英语（专）七部分结构。</p></section><section className="library"><div className="sectionTitle"><div><p className="eyebrow">学习目录</p><h2>选择单元</h2></div><span className="progressBadge">2 套试卷</span></div><button className="unitCard" onClick={()=>setUnitOpen(v=>!v)}><span className="unitNumber">01</span><span className="unitInfo"><strong>Foreign Language Learning</strong><span>外语学习 · Text A & Text B</span></span><span className="paperCount">2 套试卷</span><span className="arrow">→</span></button>{unitOpen&&<div className="paperPanel"><div className="panelHeading"><p>Unit 1 · Foreign Language Learning</p><h2>选择一套完整试卷</h2></div><div className="paperGrid">{papers.map(p=><article className="paperCard" key={p.id}><div className="paperTop"><span>0{p.id}</span><em>{p.level}</em></div><h3>{p.title}</h3><p>51题 · 150分钟 · 满分100分 · 交卷后查看答案解析</p><dl><div><dt>客观题</dt><dd>70分</dd></div><div><dt>写作</dt><dd>30分</dd></div></dl><button className="startButton" onClick={()=>start(p)}>开始答题 <span>→</span></button></article>)}</div></div>}</section></main>;
 const choice=(q:ChoiceQuestion)=><Question key={q.id} id={q.id} submitted={submitted} correct={choiceCorrect(q)} answer={q.options[q.answer]} explanation={q.explanation}><p>{q.id}. {q.prompt}</p><Options id={q.id} options={q.options} value={answers[q.id]} disabled={submitted} onChange={v=>set(q.id,v)}/></Question>;
 const match=(id:number,prompt:string,opts:string[],answer:number,explanation:string)=><Question key={id} id={id} submitted={submitted} correct={matchCorrect(id,answer)} answer={opts[answer]} explanation={explanation}><p>{id}. {prompt}</p><Options id={id} options={opts} value={answers[id]} disabled={submitted} onChange={v=>set(id,v)}/></Question>;
 return <main className="examShell"><header className="examHeader"><button onClick={()=>setPaper(null)}>← 返回 Unit 1</button><div><strong>{paper.title}</strong><span>内容来源：Unit 1</span></div><span>150分钟 · 100分</span></header><div className="examLayout"><article className="examPaper"><div className="examIntro"><p>高等教育自学考试英语（专）模拟试题</p><h1>{paper.title}</h1><div><span>课程代码 13124</span><span>51题</span><span>满分100分</span></div></div>
 <Section title="第一部分：阅读判断（第1～10题，每题1分，共10分）" instruction="阅读短文，根据文章内容选择A（正确）、B（错误）或C（未提及）。" passageTitle={paper.judgment.title} passage={paper.judgment.passage}>{paper.judgment.questions.map(choice)}</Section>
 <Section title="第二部分：阅读选择（第11～15题，每题2分，共10分）" instruction="阅读短文，从每题所给的4个选项中选出最佳选项。" passageTitle={paper.reading.title} passage={paper.reading.passage}>{paper.reading.questions.map(choice)}</Section>
 <Section title="第三部分：概括段落大意和补全句子（第16～25题，每题1分，共10分）" instruction="Task 1：为第①～⑤段分别选择正确的段落大意；Task 2：根据短文内容补全句子。" passageTitle={paper.matching.title} passage={paper.matching.passage}><h3 className="taskTitle">Task 1</h3>{paper.matching.paragraphAnswers.map((a,i)=>match(16+i,`Paragraph ${i+1}`,paper.matching.paragraphOptions,a,paper.matching.explanations[i]))}<h3 className="taskTitle">Task 2</h3>{paper.matching.sentenceAnswers.map((a,i)=>match(21+i,["A clear purpose helps learners ____.","Repeated contact helps learners ____.","Recording phrases in context helps learners ____.","Using language helps learners ____.","Weekly review helps learners ____."][i],paper.matching.sentenceOptions,a,paper.matching.explanations[5+i]))}</Section>
 <Section title="第四部分：填句补文（第26～30题，每题2分，共10分）" instruction="短文有5处空白，短文后有6个句子，其中5个取自短文，请将其分别放回原有位置。" passageTitle={paper.sentenceFill.title}><GapPassage parts={paper.sentenceFill.passageParts} start={26}/><div className="bank">{paper.sentenceFill.options.map((x,i)=><span key={x}>{String.fromCharCode(65+i)}. {x}</span>)}</div>{paper.sentenceFill.answers.map((a,i)=>match(26+i,`第 ${26+i} 空`,paper.sentenceFill.options,a,paper.sentenceFill.explanations[i]))}</Section>
 <Section title="第五部分：填词补文（第31～40题，每题1.5分，共15分）" instruction="短文有10处空白，短文后列出12个词，其中10个取自短文，请将其分别放回原有位置。" passageTitle={paper.wordFill.title}><GapPassage parts={paper.wordFill.passageParts} start={31}/><div className="bank words">{paper.wordFill.options.map((x,i)=><span key={x}>{String.fromCharCode(65+i)}. {x}</span>)}</div>{paper.wordFill.answers.map((a,i)=>match(31+i,`第 ${31+i} 空`,paper.wordFill.options,a,paper.wordFill.explanations[i]))}</Section>
 <Section title="第六部分：完形补文（第41～50题，每题1.5分，共15分）" instruction="短文有10处空白，每处空白后的括号内有一个词，请根据短文内容将其正确形式填入文中。" passageTitle={paper.wordForm.title}><FormPassage paper={paper}/>{paper.wordForm.answers.map((a,i)=><Question key={41+i} id={41+i} submitted={submitted} correct={textCorrect(41+i,a)} answer={a} explanation={paper.wordForm.explanations[i]}><label className="textAnswer">{41+i}. ({paper.wordForm.roots[i]})<input value={String(answers[41+i]??"")} disabled={submitted} onChange={e=>set(41+i,e.target.value)}/></label></Question>)}</Section>
 <Section title="第七部分：短文写作（第51题，30分）" instruction="根据所给任务完成一篇约80词的英文短文。"><div className="essayPrompt">{paper.essay.prompt}</div><textarea className="essayBox" value={essay} disabled={submitted} onChange={e=>setEssay(e.target.value)} placeholder="在这里输入英文作文……"/><p className="wordCount">约 {essay.trim()?essay.trim().split(/\s+/).length:0} 词</p>{submitted&&<div className="analysis"><strong>参考范文</strong><p>{paper.essay.sample}</p><strong>解析</strong><p>{paper.essay.analysis}</p></div>}</Section>
 {!submitted?<button className="submitExam" onClick={()=>{if(confirm(`已完成 ${Object.keys(answers).length}/50 道客观题，确定交卷吗？`)){setSubmitted(true);scrollTo(0,0)}}}>提交试卷</button>:<div className="resultCard"><p>客观题得分</p><strong>{objectiveScore} / 70</strong><span>作文按参考范文与评分提示自评（30分）</span><button onClick={()=>start(paper)}>重新练习</button></div>}
 </article><aside className="answerCard"><strong>答题卡</strong><div>{Array.from({length:50},(_,i)=><a key={i} href={`#q-${i+1}`} className={answers[i+1]!==undefined?"done":""}>{i+1}</a>)}</div><p>已答 {Object.keys(answers).length} / 50</p></aside></div></main>
}

function Section({title,instruction,passageTitle,passage,children}:{title:string;instruction:string;passageTitle?:string;passage?:string;children:React.ReactNode}){return <section className="questionSection"><h2>{title}</h2><p className="instruction">{instruction}</p>{passageTitle&&<h3 className="passageTitle">{passageTitle}</h3>}{passage&&<div className="passage">{passage.split("\n").map((p,i)=><p key={i}>{p}</p>)}</div>}{children}</section>}
function Options({id,options,value,disabled,onChange}:{id:number;options:string[];value:number|string|undefined;disabled:boolean;onChange:(v:number)=>void}){return <div className="options">{options.map((x,i)=><label key={x}><input type="radio" name={`q${id}`} checked={value===i} disabled={disabled} onChange={()=>onChange(i)}/><span>{x}</span></label>)}</div>}
function Question({id,submitted,correct,answer,explanation,children}:{id:number;submitted:boolean;correct:boolean;answer:string;explanation:string;children:React.ReactNode}){return <div id={`q-${id}`} className={`question ${submitted?(correct?"correct":"wrong"):""}`}>{children}{submitted&&<div className="analysis"><strong>{correct?"回答正确":`正确答案：${answer}`}</strong><p>{explanation}</p></div>}</div>}
function GapPassage({parts,start}:{parts:string[];start:number}){return <div className="passage gapPassage">{parts.map((p,i)=><span key={i}>{p}{i<parts.length-1&&<b>　{start+i}　</b>}</span>)}</div>}
function FormPassage({paper}:{paper:Paper}){return <div className="passage gapPassage">{paper.wordForm.passageParts.map((p,i)=><span key={i}>{p}{i<10&&<b>　{41+i}　({paper.wordForm.roots[i]})</b>}</span>)}</div>}
