export type UnitCoverage={
 unit:number;
 textAFacts:string[];
 textBFacts:string[];
 vocabulary:string[];
 phrases:string[];
 exerciseFocus:string[];
};

// Coverage inventory transcribed from each unit's New Words, Phrases and
// Expressions, Key Sentences, and the central events/arguments of Text A/B.
export const unitCoverage:UnitCoverage[]=[
 {unit:2,
  textAFacts:["An Indian water bearer carried one perfect pot and one cracked pot.","The cracked pot felt ashamed because it delivered only half a load.","The bearer had planted flower seeds on the cracked pot's side of the path.","The pot's flaw watered the flowers and gave its existence a useful purpose."],
  textBFacts:["A traveler who valued humility went sightseeing in Washington, D.C.","He wrongly assumed that an elderly woman extending her hand was asking for money.","The woman only wanted help finding the post office, and the incident exposed his prejudice.","Remembering his own immigrant family's hard work restored his humility."],
  vocabulary:["cracked","bearer","pot","pole","crack","deliver","portion","stream","master","accomplishment","imperfection","miserable","perceive","bitter","apologize","load","flaw","compassion","trail","reply","decorate","grace","moral","being","humility","sightseeing","treasure","fellow","unfortunate","panhandler","folk","elderly","extend","reflex","prejudice","assume","incident","reawaken","core","reaffirm","immigrant","no-nonsense","roofer","cashier","mechanic","humble","eventually","busboy","witness","self-induced"],
  phrases:["be ashamed of","leak out","feel sorry for","take notice of","cheer up","take advantage of","take a trip","in an instant","lose sight of","loose change"],exerciseFocus:["identify the cracked pot story's moral and supporting details","distinguish flaw, imperfection, compassion, reply and related word forms","complete a context passage about removing an obstacle","translate and reflect on humility, prejudice and judging other people"]},
 {unit:3,
  textAFacts:["The Bus Chick chooses public transit in Seattle and treats it as a civic manifesto.","Bus travel brings independence, contact with peers, and unexpected human stories.","Public transportation reduces pollution, urban sprawl, fuel use, and traffic fatalities.","The author presents every transport choice as meaningful rather than insignificant."],
  textBFacts:["Cycling to work can save purchase, fuel, parking, and running costs.","Cycle-to-work schemes and leasing incentives lower the initial financial barrier.","A brisk ride improves aerobic fitness, well-being, alertness, and concentration.","Regular cycling combines environmental, economic, physical, and social benefits."],
  vocabulary:["manifesto","privilege","rarely","coupe","haunt","primary","symbolize","slippery","independence","practical","sensible","peer","occasional","assistance","beckon","transportation","available","gossip","propaganda","transition","commute","aware","negative","impact","sprawl","fatality","inconvenience","eavesdrop","toddler","nap","camaraderie","vibrant","majesty","sacred","resource","petrol","intention","footprint","expend","abstract","purchase","kit","individual","sceptic","average","offset","incentive","generate","scheme","lease","toxic","well-being","aerobic","boost","fitness","brisk","concentration","alertness","edge","promotion"],
  phrases:["on demand","except for","believe in","in principle","in general","depending on","end up","in terms of","make sense","bear in mind"],exerciseFocus:["identify the Bus Chick manifesto's claims and evidence","use transit vocabulary including independence, resource and occasional","compare the economic, physical and environmental benefits of cycling","apply invitation-letter conventions and unit translation patterns"]},
 {unit:4,
  textAFacts:["Two sisters who argued in childhood gradually formed a lifelong friendship.","Shared memories, family experiences, and adult responsibilities strengthened their bond.","The narrator became her sister's maid of honor and values what only they can share.","The greatest gift is a relationship that survives rivalry, distance, and change."],
  textBFacts:["The colors argue loudly about which one is superior and most important.","Each color represents a distinctive contribution such as life, hope, warmth, or peace.","Rain reminds them that no single color can dominate the others.","Their cooperation creates a rainbow, a sign of friendship and shared value."],
  vocabulary:["kindergarten","lifelong","sibling","fulfillment","favoritism","bitterness","bonding","serenity","chuckle","scarce","precious","vitamin","pumpkin","mango","boast","papaya","convinced","superiority","striking","startling","stand","flash","boom","cause","relentlessly","passion","crouch","poinsettia","comfort","clamor","dominate","chief","bishop","unique","stretch","authority","reminder","indigo","determination","reflection","twilight"],
  phrases:["you name it","long for","get along with","blow your own trumpet","be willing to","in the midst of","stand for","not like somebody"],exerciseFocus:["trace the sisters' lifelong relationship and infer its central gift","practise friendship vocabulary such as sibling, bonding and favoritism","organize the colors' claims and the rainbow resolution","write a specific and sincere thank-you letter"]},
 {unit:5,
  textAFacts:["Music crosses linguistic and cultural boundaries as a universal language.","Rhythm can change pulse and energy while melody can affect emotion and memory.","Music supports productivity, creativity, comfort, motivation, and social connection.","Different genres and personal perspectives explain why musical responses vary."],
  textBFacts:["Anticipating a vacation can be as valuable as the trip itself.","A vacation interrupts routine and acts as a marker in the pattern of life.","Travel offers adventure, coincidence, restored energy, and a new perspective.","Even a short getaway creates mental space and helps people return refreshed."],
  vocabulary:["tune","personal","definition","vary","bucket","variety","genre","perspective","pump","productive","creativity","aspect","instrument","imagination","crave","addiction","tension","inspiration","universal","comfort","motivation","warehouse","brochure","getaway","standard","routine","sample","relaxation","suitcase","pack","relation","stretch","permanent","pinpoint","temporary","afterwards","adventure","coincidence","potential","restore","pattern","suspended animation","grind","space","landmark","marker"],
  phrases:["relate to","go hand in hand","look forward to","in preparation for","for some reason","at the same time","switch off","get away"],exerciseFocus:["explain how music affects body, emotion, creativity and productivity","use music vocabulary such as genre, tune, rhythm and instrument in context","sequence the preparation, anticipation and restoration stages of a vacation","develop an 80-word leisure or vacation composition with clear reasons"]},
 {unit:6,
  textAFacts:["A teacher asked students to write about what they wanted to become.","Monty described a 200-acre horse ranch in great detail and included a diagram.","The teacher gave the paper an F because the dream seemed unrealistic.","Monty refused to surrender the dream, later owned the ranch, and framed the original paper."],
  textBFacts:["Three swimmers entered a race, including an awkward and exhausted contender.","The least skilled athlete suffered a false start and struggled through the freestyle event.","The crowd moved from laughter to respect as the swimmer continued.","Courage, effort, and courtesy mattered more than finishing first."],
  vocabulary:["ranch","fund-raising","trainer","stable","race","track","career","continually","senior","describe","diagram","acre","location","detailed","square","project","unrealistic","original","breeding","stock","stud","fee","reconsider","grade","decision","assemble","frame","fireplace","stealer","fortunately","gumption","incredible","sheer","guts","event","block","freestyle","contender","desperate","stroke","exhausted","awkward","courtesy","athlete","arrogantly","quality"],
  phrases:["as a result","in detail","the other night","come across","be out for","let alone","keep a dream","go for it","false start"],exerciseFocus:["reconstruct Monty's ranch plan, the F grade and his final decision","practise dream-planning vocabulary and word formation","compare winning a race with showing courage and courtesy","use polite request patterns and verb forms in practical writing"]},
 {unit:7,
  textAFacts:["A severely injured man was interviewed after emergency surgery and intensive care.","Despite scars and pain, he deliberately chose a hopeful interpretation of events.","He treated each day as a gift and motivated the medical staff around him.","The story argues that attitude, more than circumstance, determines altitude."],
  textBFacts:["Attitude is compared with software that can be installed and monitored.","Negative habits include self-criticism, pessimism, self-pity, and resentment.","Self-encouragement and humor can interrupt a pattern of self-defeat.","People cannot control every event, but they can take responsibility for their responses."],
  vocabulary:["motivator","effective","effect","situation","consciousness","curious","mood","victim","junk","company","accident","communications","release","scar","scared","paramedic","emergency room","burly","attitude","self-pity","heartache","physical","monitor","software","performance","behavior","seminar","fundamental","inaccurate","self-criticism","pessimistic","self-encouragement","self-defeat","encounter","optimistic","habitual","self-esteem","resentment","inability","baggage","awareness","install","decline","intensive"],
  phrases:["cut away","reflect on","take action","be allergic to","thanks to","have control over","wear down","cheer on","figure out","on top of"],exerciseFocus:["infer why the injured speaker acts as a motivator","use emergency, attitude and recovery vocabulary accurately","contrast self-criticism and self-pity with constructive self-encouragement","organize a practical response to a setback using cause and effect"]},
 {unit:8,
  textAFacts:["Human beings live with mysteries that science and certainty cannot fully remove.","Life contains injustice, loss, darkness, and questions without simple answers.","The same mysterious existence also creates an infinite capacity for love.","Embracing mystery means bearing witness to suffering while reaching out with hope."],
  textBFacts:["Research is presented as a state of mind rather than work limited to laboratories.","Everyday puzzles can be approached by defining a problem and examining evidence.","Failure and obstacles are useful when they eliminate wrong explanations.","Patience, persistence, intelligent organization, and suitable apparatus support discovery."],
  vocabulary:["survive","biology","hostage","embrace","mystery","terrain","universe","otherwise","infant","tragedy","injustice","innocent","species","physiology","capacity","infinite","conceive","incline","certainty","urge","impulse","envision","inconsequential","shell","restless","murmur","vast","magical","membrane","challenge","research","persistence","misunderstanding","conception","examine","mysterious","scientific","apparatus","emphasize","solution","obstacle","elimination","intelligent","individual","discourage","failure","direction","organize"],
  phrases:["for certain","in violation of","reach out","bear witness to","state of mind","by contrast","a step in the right direction","rule out","be worth the effort"],exerciseFocus:["interpret mystery, injustice and the capacity for love in Text A","practise mystery and research word families in context","apply problem, evidence, elimination and persistence to an everyday investigation","organize and translate contrasting claims about certainty and discovery"]},
 {unit:9,
  textAFacts:["An elderly speaker says the most exciting thing is whatever she is doing now.","She rejects the idea that excitement must be a rare or spectacular event.","A near-death experience strengthened her appreciation of ordinary moments.","Attention, kindness, and presence make each minute count."],
  textBFacts:["A quiet forest dweller regularly cleared leaves, branches, and silt from a mountain spring.","After officials dismissed him, debris accumulated and the water became foul.","The mill stopped, visitors left, and the village lost the benefits it had taken for granted.","Restoring the keeper's work made the spring clear again and proved the value of faithful maintenance."],
  vocabulary:["volunteer","surprised","experience","powerful","senior moment","near-death experience","regular","confess","insult","appreciate","repeat","imply","basic","chaplain","Senate","dweller","slope","councilman","debris","crevice","faithful","regularity","remove","silt","pollution","attraction","graceful","float","irrigate","picturesque","description","council","semiannual","budget","obscure","ranger","unanimous","sparkling","tint","slimy","film","foul","odor","detect","embarrassed","fast","spring","millwheel"],
  phrases:["drop in on","from time to time","in a sense","not that I know of","bring somebody to their knees","clear away","wipe away","dispense with","grind to a halt","clear up","cling to","take for granted"],exerciseFocus:["explain why the present activity can be the most exciting thing","use time, experience and appreciation vocabulary in context","sequence the spring keeper's removal, decline and restoration","translate and reflect on unnoticed work and faithful maintenance"]},
 {unit:10,
  textAFacts:["Advertisers treat children as a prime market and use persuasive emotional techniques.","Costumes, make-up, characters, caffeine, and excitement connect products with pleasure.","Children may pester parents because they cannot easily recognize a commercial ploy.","The text raises a moral dilemma about corporations deliberately targeting naive audiences."],
  textBFacts:["Media images create an illusion of flawless bodies and immaculate lives.","Teenagers may idolize celebrities and develop insecurity, self-doubt, or eating disorders.","Sugar-coated images cover up editing, pressure, and private problems.","Young people should resist conformity and hold fast to a realistic self-image."],
  vocabulary:["advertise","prime","dilemma","persuasive","locker","expose","prod","pester","rife","association","reaction","deliberate","campaign","ploy","caffeine","corporation","extraordinarily","genuinely","costume","make-up","bunch","naive","moral","sway","superficial","specifically","target","illusion","perfection","insecurity","disorder","anorexia","habitually","celebrity","skinny","flawless","self-image","issue","stunning","drool","admiration","protrude","sugar-coated","typical","teenage","immaculate","succumb","role model","idolize","promote","strive","self-doubt","conviction","obsess"],
  phrases:["care about","appeal to","be exposed to","live up to","give in","fall victim to","look up to","consist of","cover up","in the hope of","not necessarily","in effect","regardless of","hold fast to","measure up to"],exerciseFocus:["identify persuasive techniques and the moral dilemma in child advertising","practise media and advertising vocabulary in authentic contexts","analyze how celebrity images create insecurity and an illusion of perfection","use logical connectors to organize a media-effects composition"]},
 {unit:11,
  textAFacts:["Active listening uses the whole body, not only the ears.","Listeners attend to facial expression, tone, manner, and other nonverbal signals.","Echoing and rephrasing allow the speaker to correct misunderstanding.","A listener must resist the temptation to interrupt or start planning a reply."],
  textBFacts:["Communication requires a sender, a clear message, and a receiver who checks meaning.","Different assumptions and vague language create barriers and disagreements.","Proper feedback can prevent arguments, workplace collapse, and damage to relationships.","Effective communicators refine messages, convey the bottom line, and create constructive chain reactions."],
  vocabulary:["facial","echo","rephrase","perform","frustrated","technique","anxious","tip","tone","truthfully","manner","signal","nonverbal","temptation","disagreement","argument","divorce","proper","collapse","fault","barrier","vital","verbal","workplace","chance","partner","percentage","establish","passively","performance","convey","sender","receiver","message","feedback","refine","loss","communication","interpretation","clarity"],
  phrases:["point of view","be aware of","be responsible for","put aside","do wonders","in other words","come up with","the bottom line","set off","chain reaction"],exerciseFocus:["identify the verbal and nonverbal behaviors of active listening","practise echoing, rephrasing and feedback vocabulary","analyze sender, receiver, message and communication barriers","organize a clear workplace or relationship message and check understanding"]},
 {unit:12,
  textAFacts:["Modern databases and electronic networks collect detailed profiles of individuals.","Ubiquitous tracking can reveal people's whereabouts, habits, exchanges, and private choices.","Large-scale surveys and linked records make surveillance easier than many users realize.","The text questions how much privacy society should compromise for convenience and security."],
  textBFacts:["Technology often promises improvement while weakening conversation and family attention.","Television, phones, and other devices can put real life on hold.","New inventions may replace activities without improving happiness or human relationships.","The double-edged nature of progress requires people to control tools instead of letting tools take over."],
  vocabulary:["coin","cell","behave","wired","metaphor","enormous","ubiquitous","whereabouts","track","survey","scale","exchange","expand","decade","electronic","profile","cyberspace","compromise","damage","advance","replace","catalyst","identify","breakdown","breakthrough","escape","empty","stimulate","trend","existence","significant","privacy","technology","surveillance","monitor","transparent","society","progress","feature","maintain"],
  phrases:["or rather","apply for","in addition to","put on hold","have no bearing on","grow up","take over","be caught up in","keep track of","on a large scale"],exerciseFocus:["explain how electronic profiles and tracking threaten privacy","practise technology, surveillance and cyberspace vocabulary","weigh convenience against damage to attention and relationships","organize a balanced composition about technology's double edge"]}
];

export const coverageFor=(unit:number)=>unitCoverage.find(item=>item.unit===unit)!;
