export type UnitCoverage={
 unit:number;
 textAFacts:string[];
 textBFacts:string[];
 vocabulary:string[];
 phrases:string[];
 exerciseFocus:string[];
 practicalWriting:{genre:string;requirements:string[];sampleContext:string};
};

// Coverage inventory transcribed from each unit's New Words, Phrases and
// Expressions, Key Sentences, and the central events/arguments of Text A/B.
export const unitCoverage:UnitCoverage[]=[
 {unit:2,
  textAFacts:["An Indian water bearer carried two pots on opposite ends of a pole.","One pot was perfect, whereas the other had a crack in its side.","After the long walk, the cracked pot delivered only half a load of water.","For two years the perfect pot felt proud while the cracked pot felt ashamed.","The cracked pot apologized because its flaw seemed to waste the bearer's effort.","The bearer asked the pot to notice the flowers along its side of the path.","He had planted seeds there because he already knew about the crack.","Water leaking from the pot helped the flowers grow every day.","The flowers decorated the master's table and gave the flaw a useful result.","The story's moral is to recognize imperfections and use them compassionately."],
  textBFacts:["A successful traveler went sightseeing in Washington, D.C., while thinking about humility.","An elderly woman extended her hand as he walked near a public building.","He instantly assumed that she was a panhandler asking him for loose change.","The woman was actually asking for directions to the post office.","Her simple question exposed the traveler's reflexive prejudice.","The incident made him lose sight of the humble values he claimed to treasure.","He remembered immigrant relatives who had worked as roofers, cashiers, mechanics and busboys.","Their no-nonsense work had formed the core of his family's progress.","The encounter reawakened his compassion and reaffirmed the value of humility.","The text warns that success can create self-induced distance from other people."],
  vocabulary:["cracked","bearer","pot","pole","crack","deliver","portion","stream","master","accomplishment","imperfection","miserable","perceive","bitter","apologize","load","flaw","compassion","trail","reply","decorate","grace","moral","being","humility","sightseeing","treasure","fellow","unfortunate","panhandler","folk","elderly","extend","reflex","prejudice","assume","incident","reawaken","core","reaffirm","immigrant","no-nonsense","roofer","cashier","mechanic","humble","eventually","busboy","witness","self-induced"],
  phrases:["be ashamed of","leak out","feel sorry for","take notice of","cheer up","take advantage of","take a trip","in an instant","lose sight of","loose change"],exerciseFocus:["identify the cracked pot story's moral and supporting details","distinguish flaw, imperfection, compassion, reply and related word forms","complete a context passage about removing an obstacle","translate and reflect on humility, prejudice and judging other people"],practicalWriting:{genre:"Notice",requirements:["time and date","place","activity and organizer"],sampleContext:"an annual town meeting and an English speaking contest"}},
 {unit:3,
  textAFacts:["As a child, the Bus Chick valued buses as a source of independence.","At sixteen she accepted the automobile industry's idea that a car symbolized adulthood.","Except for a short college period, she left buses behind for about ten years.","A job fifteen miles outside Seattle made the effects of daily car commuting visible.","She connected car culture with pollution, sprawl, isolation and traffic fatalities.","After returning to transit, she used her silver coupe so rarely that she sold it in March 2003.","Rain, slippery floors, fogged windows and crowded rides are admitted inconveniences.","Bus travel also creates conversations, gossip, children, music and camaraderie among riders.","The manifesto links transit with clean air, vibrant cities and protection of Puget Sound.","Its conclusion insists that individual transport choices matter and collective change is possible."],
  textBFacts:["Cycling removes or reduces the purchase, fuel, parking and maintenance costs of a car.","Government-supported cycle-to-work schemes can reduce the initial price of equipment.","Leasing and tax incentives allow workers to spread or offset bicycle costs.","A bicycle journey produces a much smaller environmental footprint than a car commute.","Cycling does not require a separate trip to a gym because exercise becomes part of the workday.","A brisk ride improves aerobic fitness and general well-being.","Physical activity can boost alertness and concentration after arrival at work.","Regular riders may avoid delays caused by traffic congestion and unpredictable parking.","Sceptics should consider practical distance, clothing, safety and route conditions rather than reject cycling in principle.","The article combines financial, environmental, physical and workplace reasons for trying bicycle commuting."],
  vocabulary:["manifesto","privilege","rarely","coupe","haunt","primary","symbolize","slippery","independence","practical","sensible","peer","occasional","assistance","beckon","transportation","available","gossip","propaganda","transition","commute","aware","negative","impact","sprawl","fatality","inconvenience","eavesdrop","toddler","nap","camaraderie","vibrant","majesty","sacred","resource","petrol","intention","footprint","expend","abstract","purchase","kit","individual","sceptic","average","offset","incentive","generate","scheme","lease","toxic","well-being","aerobic","boost","fitness","brisk","concentration","alertness","edge","promotion"],
  phrases:["on demand","except for","believe in","in principle","in general","depending on","end up","in terms of","make sense","bear in mind"],exerciseFocus:["identify the Bus Chick manifesto's claims and evidence","use transit vocabulary including independence, resource and occasional","compare the economic, physical and environmental benefits of cycling","apply invitation-letter conventions and unit translation patterns"],practicalWriting:{genre:"Letter of Invitation",requirements:["purpose and event","date, time and place","polite closing and reply request"],sampleContext:"an invitation to an Ideal Home Exhibition and a wedding invitation"}},
 {unit:4,
  textAFacts:["The narrator and her sister competed and argued when they were children.","Favoritism and ordinary sibling rivalry sometimes produced bitterness.","Growing older allowed them to understand experiences that no outsider shared.","Family memories became a private history connecting childhood with adult life.","Distance and changing responsibilities did not end their bond.","They could chuckle over old conflicts that had once seemed serious.","The narrator served as her sister's maid of honor.","They supported each other during scarce, difficult and joyful periods.","Their relationship brought serenity and fulfillment rather than constant agreement.","The text presents a sister who becomes a friend as a precious lifelong gift."],
  textBFacts:["Green claims superiority because it represents life, nature and hope.","Blue associates itself with sky, sea, peace and serenity.","Yellow boasts of sunshine, warmth, laughter and happiness.","Orange points to health, strength and foods such as carrots, pumpkins and mangoes.","Red presents itself as blood, danger, courage and passion.","Purple invokes royalty, authority, bishops and power.","Indigo speaks more quietly but represents thought, reflection and twilight.","The colors' clamour grows until thunder and rain interrupt their argument.","Rain tells them that each color is unique and none should dominate.","Stretching together across the sky, they form a rainbow that symbolizes cooperation and friendship."],
  vocabulary:["kindergarten","lifelong","sibling","fulfillment","favoritism","bitterness","bonding","serenity","chuckle","scarce","precious","vitamin","pumpkin","mango","boast","papaya","convinced","superiority","striking","startling","stand","flash","boom","cause","relentlessly","passion","crouch","poinsettia","comfort","clamor","dominate","chief","bishop","unique","stretch","authority","reminder","indigo","determination","reflection","twilight"],
  phrases:["you name it","long for","get along with","blow your own trumpet","be willing to","in the midst of","stand for","not like somebody"],exerciseFocus:["trace the sisters' lifelong relationship and infer its central gift","practise friendship vocabulary such as sibling, bonding and favoritism","organize the colors' claims and the rainbow resolution","write a specific and sincere thank-you letter"],practicalWriting:{genre:"Thank-You Letter",requirements:["identify the thoughtful act or gift","give specific details","express heartfelt appreciation"],sampleContext:"thanking friends for a family visit, meals and practical help"}},
 {unit:5,
  textAFacts:["People give different personal definitions of music because their tastes and experiences vary.","The range of musical genres allows listeners to choose sounds suited to different needs.","A strong rhythm can affect pulse, physical energy and the desire to move.","A familiar tune can bring back memories connected with a person, place or period of life.","Music may reduce tension and provide comfort during difficult or lonely moments.","Some listeners use energetic music to increase motivation during exercise or routine work.","Suitable background music can support productivity, although distracting music may have the opposite effect.","Playing an instrument develops coordination, attention and disciplined practice.","Creating or interpreting music gives imagination and creativity a practical outlet.","Because it communicates emotion across linguistic boundaries, music is often described as a universal language."],
  textBFacts:["Looking forward to a vacation creates pleasure before the journey begins.","Brochures, routes, reservations and packing turn anticipation into preparation.","A getaway interrupts the standard routine and gives ordinary responsibilities a temporary pause.","Travel can create adventure through unfamiliar places and unplanned events.","Coincidences and encounters may become more memorable than the original schedule.","Distance from the daily grind provides mental space for reflection.","Rest and a change of activity can restore energy rather than simply fill time.","A vacation acts as a marker that divides one period of life from another.","Even a short trip can alter perspective when it is genuinely different from everyday routine.","The value of a vacation continues afterwards through memories, renewed attention and a refreshed return."],
  vocabulary:["tune","personal","definition","vary","bucket","variety","genre","perspective","pump","productive","creativity","aspect","instrument","imagination","crave","addiction","tension","inspiration","universal","comfort","motivation","warehouse","brochure","getaway","standard","routine","sample","relaxation","suitcase","pack","relation","stretch","permanent","pinpoint","temporary","afterwards","adventure","coincidence","potential","restore","pattern","suspended animation","grind","space","landmark","marker"],
  phrases:["relate to","go hand in hand","look forward to","in preparation for","for some reason","at the same time","switch off","get away"],exerciseFocus:["explain how music affects body, emotion, creativity and productivity","use music vocabulary such as genre, tune, rhythm and instrument in context","sequence the preparation, anticipation and restoration stages of a vacation","develop an 80-word leisure or vacation composition with clear reasons"],practicalWriting:{genre:"Letter of Complaint",requirements:["state the service or product problem","describe evidence and its effect","request a fair response"],sampleContext:"complaining about rude service from a shop assistant"}},
 {unit:6,
  textAFacts:["As a high-school senior, Monty Roberts was asked to describe what he wanted to become.","His childhood had been spent moving from stable to stable with his horse-trainer father.","Monty wrote a seven-page paper describing his dream of owning a horse ranch.","He included a detailed diagram of a 200-acre ranch and a 4,000-square-foot house.","The teacher marked the paper F because the project required money and resources Monty did not have.","The teacher offered to reconsider the grade if Monty rewrote the paper with a more realistic goal.","After reflecting, Monty returned the same paper and chose to keep both the F and his dream.","Years later he owned the ranch and house that he had described.","The original school paper was framed over the fireplace as evidence of persistence.","The teacher later admitted that adults can steal dreams and praised Monty for holding on to his."],
  textBFacts:["Three swimmers prepared for a freestyle event with very different levels of ability.","One contender looked awkward and far less experienced than the others.","A false start increased the pressure before the race properly began.","The strongest swimmers moved ahead while the struggling athlete used desperate, uneven strokes.","Exhaustion made every remaining length a test of courage rather than speed.","Some spectators initially reacted to the swimmer's performance with amusement.","As the athlete continued instead of leaving the pool, laughter gave way to support.","The crowd cheered the last swimmer's effort even though victory was impossible.","The event exposed the arrogance of judging worth only by first place.","The story presents sheer guts, perseverance and courtesy as qualities more important than winning."],
  vocabulary:["ranch","fund-raising","trainer","stable","race","track","career","continually","senior","describe","diagram","acre","location","detailed","square","project","unrealistic","original","breeding","stock","stud","fee","reconsider","grade","decision","assemble","frame","fireplace","stealer","fortunately","gumption","incredible","sheer","guts","event","block","freestyle","contender","desperate","stroke","exhausted","awkward","courtesy","athlete","arrogantly","quality"],
  phrases:["as a result","in detail","the other night","come across","be out for","let alone","keep a dream","go for it","false start"],exerciseFocus:["reconstruct Monty's ranch plan, the F grade and his final decision","practise dream-planning vocabulary and word formation","compare winning a race with showing courage and courtesy","use polite request patterns and verb forms in practical writing"],practicalWriting:{genre:"Formal Request Letter",requirements:["state the request clearly","provide evidence that it is justified","use a courteous tone"],sampleContext:"requesting continued scholarship assistance for medical education"}},
 {unit:7,
  textAFacts:["The narrator knew a consistently cheerful manager who motivated people around him.","When asked about his positive mood, the manager explained that attitude involved daily choices.","He chose to learn from bad situations instead of behaving like a helpless victim.","During a robbery, he was shot and left seriously wounded.","Paramedics took him to an emergency room where the expressions of medical staff frightened him.","A burly nurse asked whether he was allergic to anything before treatment.","He answered that he was allergic to bullets, using humor in a life-threatening moment.","He told the surgical team to operate on him as a living person, not as someone already defeated.","After intensive care and recovery, scars remained but his chosen attitude did not change.","His experience supports the claim that attitude, rather than circumstance alone, determines altitude."],
  textBFacts:["Attitude is described as mental software that influences performance and behavior.","People should monitor repeated thoughts just as they would monitor a computer programme.","Inaccurate self-criticism can become habitual and damage self-esteem.","Pessimistic predictions make obstacles seem final before action has been attempted.","Self-pity focuses attention on heartache while reducing a person's sense of control.","Resentment preserves emotional baggage instead of solving the original problem.","Constructive self-encouragement can challenge the language of self-defeat.","Humor and awareness help interrupt a negative reaction before it becomes a habit.","An optimistic attitude does not deny difficulty; it supports a more useful response to it.","People cannot control every encounter, but they can accept responsibility for the attitude they install and practise."],
  vocabulary:["motivator","effective","effect","situation","consciousness","curious","mood","victim","junk","company","accident","communications","release","scar","scared","paramedic","emergency room","burly","attitude","self-pity","heartache","physical","monitor","software","performance","behavior","seminar","fundamental","inaccurate","self-criticism","pessimistic","self-encouragement","self-defeat","encounter","optimistic","habitual","self-esteem","resentment","inability","baggage","awareness","install","decline","intensive"],
  phrases:["cut away","reflect on","take action","be allergic to","thanks to","have control over","wear down","cheer on","figure out","on top of"],exerciseFocus:["infer why the injured speaker acts as a motivator","use emergency, attitude and recovery vocabulary accurately","contrast self-criticism and self-pity with constructive self-encouragement","organize a practical response to a setback using cause and effect"],practicalWriting:{genre:"Letter of Apology",requirements:["give an account of the offence","admit responsibility and explain","express remorse and ask forgiveness"],sampleContext:"apologizing for missing an arranged lunch"}},
 {unit:8,
  textAFacts:["Human survival does not remove the mysteries surrounding biology, consciousness and the universe.","An infant's existence can inspire wonder even when physiology explains many physical processes.","Tragedy and injustice raise questions that certainty cannot settle.","The suffering of innocent people violates the expectation that life should always be fair.","Human beings nevertheless possess an immense capacity to care for one another.","Love cannot be reduced to a simple formula even though its effects can be witnessed.","The urge to reach out is meaningful even when it seems inconsequential on a vast scale.","Mystery can make people restless because it denies a complete and final explanation.","Embracing mystery does not require ignoring darkness or pretending suffering is magical.","It means bearing witness to pain while envisioning hope and remaining open to love."],
  textBFacts:["Research is a state of mind and is not confined to professional laboratories.","An everyday mystery becomes research when a person defines the problem clearly.","A first explanation should be treated as a conception to examine rather than a conclusion to defend.","Evidence must be collected in an organized and intelligent way.","Appropriate apparatus may help, but tools cannot replace a well-framed question.","Failure is informative when it rules out an incorrect explanation.","An obstacle can indicate that the method or direction needs adjustment.","Persistence is necessary because useful evidence may appear slowly.","Researchers should not become discouraged merely because an early attempt fails.","Step-by-step elimination and careful observation make the effort worthwhile and move inquiry toward a solution."],
  vocabulary:["survive","biology","hostage","embrace","mystery","terrain","universe","otherwise","infant","tragedy","injustice","innocent","species","physiology","capacity","infinite","conceive","incline","certainty","urge","impulse","envision","inconsequential","shell","restless","murmur","vast","magical","membrane","challenge","research","persistence","misunderstanding","conception","examine","mysterious","scientific","apparatus","emphasize","solution","obstacle","elimination","intelligent","individual","discourage","failure","direction","organize"],
  phrases:["for certain","in violation of","reach out","bear witness to","state of mind","by contrast","a step in the right direction","rule out","be worth the effort"],exerciseFocus:["interpret mystery, injustice and the capacity for love in Text A","practise mystery and research word families in context","apply problem, evidence, elimination and persistence to an everyday investigation","organize and translate contrasting claims about certainty and discovery"],practicalWriting:{genre:"Suggestion Letter",requirements:["identify an existing problem","offer a specific workable solution","anticipate the reader's response and remain courteous"],sampleContext:"suggesting ways to reduce employee turnover"}},
 {unit:9,
  textAFacts:["An elderly volunteer is asked to identify the most exciting thing she has ever done.","She surprises the interviewer by saying that the most exciting thing is what she is doing now.","The answer rejects the assumption that excitement must belong to an extraordinary past event.","She admits that memory can sometimes fail in an ordinary senior moment.","A near-death experience made the value of present time especially clear to her.","She does not claim that every moment is pleasant or free from difficulty.","Instead, she pays full attention to the person and activity immediately before her.","Repeating appreciation as a daily practice keeps experience from becoming automatic.","Her idea treats each minute as an opportunity for interest, kindness and participation.","The central lesson is that making time count depends more on presence than on spectacular events."],
  textBFacts:["An old forest dweller quietly cared for a spring on a mountain slope.","With faithful regularity he removed leaves, branches and silt from its pools and crevices.","The clear spring supplied water that turned a millwheel and irrigated farms below.","Its sparkling flow added to the picturesque village and attracted visitors.","During a semiannual budget review, council members questioned the payment to an obscure spring keeper.","They unanimously decided to dispense with his services because his work was largely unseen.","Without regular clearing, debris accumulated and the water developed a dark tint, slimy film and foul odor.","The mill ground to a halt, visitors stayed away and the village became embarrassed by the pollution.","Officials restored the keeper, and the spring gradually became clear again.","The story shows how communities take faithful maintenance for granted until its benefits disappear."],
  vocabulary:["volunteer","surprised","experience","powerful","senior moment","near-death experience","regular","confess","insult","appreciate","repeat","imply","basic","chaplain","Senate","dweller","slope","councilman","debris","crevice","faithful","regularity","remove","silt","pollution","attraction","graceful","float","irrigate","picturesque","description","council","semiannual","budget","obscure","ranger","unanimous","sparkling","tint","slimy","film","foul","odor","detect","embarrassed","fast","spring","millwheel"],
  phrases:["drop in on","from time to time","in a sense","not that I know of","bring somebody to their knees","clear away","wipe away","dispense with","grind to a halt","clear up","cling to","take for granted"],exerciseFocus:["explain why the present activity can be the most exciting thing","use time, experience and appreciation vocabulary in context","sequence the spring keeper's removal, decline and restoration","translate and reflect on unnoticed work and faithful maintenance"],practicalWriting:{genre:"Letter of Congratulations",requirements:["congratulate the reader","say where the news was learned","add praise and good wishes"],sampleContext:"congratulating new parents on the birth of their baby"}},
 {unit:10,
  textAFacts:["Children are a prime market because they influence both present purchases and future brand habits.","Advertising exposes young viewers to persuasive messages before they can evaluate them critically.","Bright costumes, make-up and familiar characters connect products with entertainment.","Music, excitement and repeated images create positive associations that may have little bearing on product quality.","Food and drink campaigns may hide caffeine, sugar or other less attractive facts.","Young children often treat an advertisement as information rather than as a deliberate sales ploy.","The resulting desire can lead them to pester parents in shops or at home.","Corporations invest heavily because campaigns aimed at children can produce extraordinarily strong reactions.","The issue is not only whether advertising works but whether a naive audience can give informed attention.","The text presents deliberate targeting of children as a moral dilemma rather than a superficial business question."],
  textBFacts:["Media images promote an illusion that successful people have flawless bodies and immaculate lives.","Teenagers may look up to celebrities without seeing the editing and commercial decisions behind an image.","Repeated comparison can create insecurity and self-doubt about normal appearance.","Extremely skinny role models may encourage unhealthy attempts to measure up.","Obsession with perfection can contribute to eating disorders such as anorexia.","Sugar-coated stories cover up private pressure, ordinary flaws and failures.","Admiration becomes dangerous when a person habitually treats a constructed image as reality.","A stunning photograph does not necessarily provide evidence of happiness or character.","Young people should resist the demand to conform regardless of their health and individuality.","Holding fast to a realistic self-image protects conviction and reduces the power of manufactured perfection."],
  vocabulary:["advertise","prime","dilemma","persuasive","locker","expose","prod","pester","rife","association","reaction","deliberate","campaign","ploy","caffeine","corporation","extraordinarily","genuinely","costume","make-up","bunch","naive","moral","sway","superficial","specifically","target","illusion","perfection","insecurity","disorder","anorexia","habitually","celebrity","skinny","flawless","self-image","issue","stunning","drool","admiration","protrude","sugar-coated","typical","teenage","immaculate","succumb","role model","idolize","promote","strive","self-doubt","conviction","obsess"],
  phrases:["care about","appeal to","be exposed to","live up to","give in","fall victim to","look up to","consist of","cover up","in the hope of","not necessarily","in effect","regardless of","hold fast to","measure up to"],exerciseFocus:["identify persuasive techniques and the moral dilemma in child advertising","practise media and advertising vocabulary in authentic contexts","analyze how celebrity images create insecurity and an illusion of perfection","use logical connectors to organize a media-effects composition"],practicalWriting:{genre:"Application Letter",requirements:["name the position or programme","connect strengths with qualifications","request consideration and provide a professional closing"],sampleContext:"a job application letter accompanying a CV"}},
 {unit:11,
  textAFacts:["Active listening is a deliberate performance involving attention rather than passive hearing.","A listener uses eyes and posture as well as ears to understand the speaker.","Facial expression can qualify or contradict the literal meaning of words.","Tone and manner signal anxiety, frustration, confidence or uncertainty.","Nonverbal signals therefore form part of the message instead of mere decoration.","Echoing a key expression shows attention and gives the speaker a chance to clarify it.","Rephrasing the message in the listener's own words checks whether meaning has been understood.","A listener should put aside a private point of view long enough to hear the speaker's actual concern.","Planning a reply while the other person is talking creates a temptation to miss important information.","Truthful, patient feedback can do wonders for trust and reduce disagreement."],
  textBFacts:["Communication begins with a sender who has an intended message.","The sender must convey the message clearly instead of assuming the receiver shares the same background.","The receiver interprets both verbal language and surrounding signals.","Vague wording and different assumptions create barriers even when neither person intends harm.","Feedback allows the receiver to state what was understood.","The sender can then refine the message before a small misunderstanding becomes an argument.","Proper communication is vital in both workplace partnerships and personal relationships.","Failure to check meaning can set off a damaging chain reaction.","Effective communicators identify the bottom line without removing necessary detail.","A complete exchange requires sender, message, receiver and feedback rather than one person simply speaking."],
  vocabulary:["facial","echo","rephrase","perform","frustrated","technique","anxious","tip","tone","truthfully","manner","signal","nonverbal","temptation","disagreement","argument","divorce","proper","collapse","fault","barrier","vital","verbal","workplace","chance","partner","percentage","establish","passively","performance","convey","sender","receiver","message","feedback","refine","loss","communication","interpretation","clarity"],
  phrases:["point of view","be aware of","be responsible for","put aside","do wonders","in other words","come up with","the bottom line","set off","chain reaction"],exerciseFocus:["identify the verbal and nonverbal behaviors of active listening","practise echoing, rephrasing and feedback vocabulary","analyze sender, receiver, message and communication barriers","organize a clear workplace or relationship message and check understanding"],practicalWriting:{genre:"Curriculum Vitae",requirements:["personal details and education","work experience and skills","relevant interests or achievements"],sampleContext:"Jason Sharpe's education, marketing work and skills CV"}},
 {unit:12,
  textAFacts:["Modern society is increasingly wired through databases, networks and electronic devices.","A digital profile can combine purchases, applications, communications and other exchanges.","Ubiquitous systems make tracking possible even when a person is not consciously using a computer.","Mobile and location records can reveal an individual's whereabouts over time.","Large-scale surveys expand the amount of personal information available for comparison.","Separate records become more revealing when organizations link them together.","Electronic profiles may be useful for service and security while also enabling surveillance.","People often compromise privacy without knowing how long information will be stored or reused.","The scale of collection has grown rapidly over recent decades.","The text asks how a transparent society can preserve individual privacy while retaining legitimate technological benefits."],
  textBFacts:["New technology is commonly presented as an advance that will improve everyday life.","Television and electronic entertainment can put direct conversation on hold.","Phones and other connected devices may interrupt attention to people who are physically present.","A new invention can replace an older activity without producing greater happiness.","Technological breakdowns reveal how dependent routines have become on systems once treated as optional.","The excitement of a breakthrough may hide damage to family or community relationships.","People caught up in constant stimulation may mistake activity for meaningful experience.","Convenient features can take over habits if users never decide when to switch them off.","Technology is a catalyst whose effect depends partly on how people choose to use it.","Because progress is double-edged, people must maintain control of tools instead of allowing tools to control life."],
  vocabulary:["coin","cell","behave","wired","metaphor","enormous","ubiquitous","whereabouts","track","survey","scale","exchange","expand","decade","electronic","profile","cyberspace","compromise","damage","advance","replace","catalyst","identify","breakdown","breakthrough","escape","empty","stimulate","trend","existence","significant","privacy","technology","surveillance","monitor","transparent","society","progress","feature","maintain"],
  phrases:["or rather","apply for","in addition to","put on hold","have no bearing on","grow up","take over","be caught up in","keep track of","on a large scale"],exerciseFocus:["explain how electronic profiles and tracking threaten privacy","practise technology, surveillance and cyberspace vocabulary","weigh convenience against damage to attention and relationships","organize a balanced composition about technology's double edge"],practicalWriting:{genre:"Personal Statement",requirements:["establish a controlling theme","develop it with detailed experience and achievements","end by widening the theme toward future goals"],sampleContext:"an MPH applicant's epidemiology preparation and professional ambition"}}
];

export const coverageFor=(unit:number)=>unitCoverage.find(item=>item.unit===unit)!;
