import type {ChoiceQuestion,Paper} from "./papers-v2";

const jq=(id:number,prompt:string,answer:number,explanation:string):ChoiceQuestion=>({id,prompt,options:["A. True","B. False","C. Not Given"],answer,explanation});
const cq=(id:number,prompt:string,options:string[],answer:number,explanation:string):ChoiceQuestion=>({id,prompt,options,answer,explanation});
const letters=(xs:string[])=>xs.map((x,i)=>`${String.fromCharCode(65+i)}. ${x}`);

const explain=(n:number,prefix:string)=>Array.from({length:n},(_,i)=>`${prefix}第${i+1}空需结合前后句的指代、逻辑关系和语法结构判断。`);

function matching(title:string,paragraphs:string[],headings:string[],answers:number[],sentences:string[],sentenceAnswers:number[]){
 return {
  title,passage:paragraphs.map((p,i)=>`${i+1}. ${p}`).join("\n\n"),
  paragraphPrompts:paragraphs.map((_,i)=>`${title} — Paragraph ${i+1}`),paragraphOptions:letters(headings),paragraphAnswers:answers,
  sentencePrompts:[`In “${title},” the first paragraph mainly asks readers to ____.`,`In “${title},” the second paragraph shows how people may ____.`,`In “${title},” the third paragraph stresses the need to ____.`,`In “${title},” the fourth paragraph recommends that we ____.`,`In “${title},” the final paragraph reminds us to ____.`],
  sentenceOptions:letters(sentences),sentenceAnswers,
  explanations:[...answers.map((a,i)=>`第${i+1}段的中心与“${headings[a]}”相符。`),...sentenceAnswers.map((a,i)=>`第${i+1}题应选“${sentences[a]}”，与对应段落的行动或结论一致。`)]
 };
}

function insertion(title:string,parts:string[],options:string[],answers:number[]){
 return {title,passageParts:parts,options:letters(options),answers,explanations:answers.map((a,i)=>`第${i+1}空选项“${options[a]}”承接前句并引出后句，逻辑和指代完整。`)};
}

function wordFill(title:string,parts:string[],options:string[],answers:number[],notes:string[]){
 return {title,passageParts:parts,options:letters(options),answers,explanations:notes};
}

function wordForm(title:string,parts:string[],roots:string[],answers:string[]){
 return {title,passageParts:parts,roots,answers,explanations:answers.map((a,i)=>`第${i+1}空在句中需要${/[ly]$/.test(a)?"副词或相应词形":"与语境和句法位置相符的词形"}，答案为 ${a}。`)};
}

const crackedPot=`A water bearer in India had two large pots. Each pot hung from one end of a pole that he carried across his neck. One pot was perfect and always delivered a full portion of water at the end of the long walk from the stream to the master's house. The other pot had a crack in its side. By the time the bearer reached the house, the cracked pot was only half full.

For two years the bearer made the same journey every day. The perfect pot was proud of its accomplishments, but the cracked pot was ashamed of its imperfection. It felt miserable because it could do only half of what it had been made to do. One day, beside the stream, it apologized to the bearer. It explained that the crack allowed water to leak out all the way home and that the bearer received only half the value of his effort.

The bearer felt compassion for the pot. He asked it to take notice of the beautiful flowers along the path on the way back. The pot did see bright flowers, but it still felt bad because half its water had again leaked away. Then the bearer explained that the flowers grew only on the cracked pot's side of the path. He had always known about the flaw, so he planted seeds there. Every day the leaking pot watered them. For two years he had picked the flowers to decorate his master's table.

Without the crack, there would have been no flowers to grace the house. The bearer had not ignored the pot's weakness; he had understood it and taken advantage of it. The story does not say that every flaw is harmless. It shows that people can recognize an imperfection, respond with compassion and discover a useful path that pride or shame might otherwise hide.`;

const humility=`A few years ago, Felipe Morales took a sightseeing trip to Washington, D.C. He admired national treasures, but he also noticed unfortunate fellow citizens on the streets, including panhandlers and homeless people. Outside the Ronald Reagan Center, he heard someone ask, “Can you help me?” Turning around, he saw an elderly blind woman with her hand extended. In a natural reflex, he reached into his pocket, took out his loose change and placed it in her hand without looking at her. He was annoyed because he assumed that she was begging.

The woman smiled and said that she did not want his money; she only needed directions to the post office. In an instant, Morales understood what he had done. He had acted out of prejudice and judged another person according to an unsupported assumption. The incident reawakened a core belief in humility that he had failed to follow for a moment.

His reaction troubled him for another reason. Morales was an immigrant who had arrived in the United States from Honduras at fifteen with his brother, sister and no-nonsense mother. Before eventually becoming a network engineer, he had worked as a dishwasher, roofer, cashier, mechanic, pizza delivery driver and busboy. At seventeen, while clearing tables, he once heard a father warn a child that poor study would make him “end up” like the busboy. Morales had also witnessed prejudice against relatives and friends.

Comfortable middle-class life had made it easy for him to lose sight of his past. The blind woman cured his self-induced blindness. She reminded him to keep his eyes and heart open. He then guided her to the post office and later wrote about the priceless lesson she had given him: humility requires us to see a person before we judge a category.`;

const paperData:Array<Omit<Paper,"coverage">>=[
{
 id:1,unit:2,unitTitle:"A Path to Follow",title:"Unit 2 模拟卷一（教材精校版）",level:"基础巩固",
 judgment:{title:"Cracked or Perfect: We Can Make a Difference!",passage:crackedPot,questions:[
  jq(1,"The perfect pot delivered a full portion of water to the master's house.",0,"首段明确说明完好的水罐每次都装满水到达主人家。"),jq(2,"The cracked pot had been damaged only a few days before it apologized.",1,"漏水的情况持续了两年，并非几天。"),jq(3,"The cracked pot felt proud of completing half its task.",1,"它因只能完成一半任务而羞愧、难过。"),jq(4,"The water bearer asked the pot to notice flowers beside the path.",0,"挑水工让它在回程中留意路旁的花。"),jq(5,"Flowers grew on both sides of the path in equal numbers.",1,"花只生长在有裂缝水罐的那一侧。"),jq(6,"The bearer planted seeds after learning about the crack.",0,"他知道缺陷，并在对应一侧播下种子。"),jq(7,"The master paid extra money for the flowers.",2,"文中没有提到主人额外付钱。"),jq(8,"The leaking water helped the flowers grow.",0,"每天漏出的水浇灌了花。"),jq(9,"The story claims that every weakness should simply be ignored.",1,"挑水工理解并利用缺陷，而不是忽视缺陷。"),jq(10,"Compassion and understanding can reveal value hidden by shame.",0,"末段点明同情、理解和重新看待缺陷的意义。") ]},
 reading:{title:"The Potter's Repair",passage:`In a village workshop, Leela taught young potters not to throw away every damaged bowl. She first examined whether a crack made an object unsafe. A cooking pot that could split over a fire had to be recycled, but a shallow bowl with a stable crack might receive a different purpose.

One student, Arun, brought her a large bowl whose rim had broken during firing. He felt ashamed because it was his first independent piece. Leela did not pretend that the bowl was perfect. She asked him to smooth the edge, seal the surface and place small stones inside it. The bowl became a planter for herbs near the workshop door.

Visitors took notice of the unusual planter. Some assumed that Leela was teaching students to accept careless work, but she explained the difference between hiding a flaw and responding to it responsibly. The class still studied measurement, temperature and careful handling. At the same time, students learned that an unsuccessful first purpose did not always remove every possible value.

Arun later kept a record of firing problems and reduced the number of damaged pieces. The repaired bowl did not lower his standards; it reminded him to combine improvement with imagination.`,questions:[
  cq(11,"What did Leela do before reusing a damaged object?",["She sold it","She checked its safety","She painted every crack","She asked visitors to decide"],1,"第一段说明她先判断裂缝是否使物品不安全。"),cq(12,"What did Arun's bowl become?",["A cooking pot","A water container","An herb planter","A museum prize"],2,"第二段明确说它被改成了香草花盆。"),cq(13,"What did some visitors wrongly assume?",["The class accepted careless work","Arun had bought the bowl","The workshop had closed","Leela disliked repairs"],0,"第三段说有人误以为她鼓励接受粗心作品。"),cq(14,"The word “standards” in the last paragraph refers to ____.",["prices","places","requirements for good work","sizes of stones"],2,"此处指对作品质量的要求。"),cq(15,"What is the main idea?",["All broken objects are safe","A flaw can be handled without abandoning improvement","Students should avoid independent work","Visitors understand craft better than potters"],1,"文章强调改进标准和创造性利用可以并存。") ]},
 matching:matching("Five Ways to Respond to an Imperfection",[
  "Recognize the flaw honestly. Shame becomes less useful when it prevents us from describing what has actually happened.","Decide whether the weakness creates real danger. Compassion does not require pretending that every damaged object or habit is harmless.","Look for a different use. The cracked pot could not deliver a full portion, yet its leaking water supported flowers along the path.","Improve what can be improved. A creative second purpose should not become an excuse for repeating avoidable mistakes.","Notice the wider result. An action may benefit people in ways that the original plan did not predict."
 ],["Consider unexpected effects","Find another possible purpose","Name the weakness clearly","Keep learning from errors","Check safety and consequences","Demand perfection first"],[2,4,1,3,0],["describe the problem without self-deception","separate compassion from carelessness","take advantage of a remaining strength","correct preventable problems","see value beyond the first goal","hide evidence of failure"],[0,1,2,3,4]),
 sentenceFill:insertion("A Path Watered by an Imperfect Pot",[
  "The cracked pot measured itself only by the water missing at the end of the journey. "," It therefore interpreted every drop on the road as evidence of failure.\n\nThe bearer saw the same drops differently. "," This choice turned an unavoidable leak into regular care for living things.\n\nHis response was compassionate but not dishonest. "," He knew exactly how much water was lost and planned around that fact.\n\nThe flowers changed the meaning of the daily walk. "," The path now showed that a weakness and a contribution could exist together.\n\nThe lesson applies to people only when it is used carefully. "," We should recognize limits, improve where possible and remain open to a purpose we did not first imagine."
 ],["It failed to take notice of what happened along the path.","He planted flower seeds on the side where the pot leaked.","He never claimed that the pot was able to carry a full portion.","They were picked to decorate and grace the master's house.","It is not an argument for ignoring every harmful flaw.","The perfect pot immediately developed a larger crack."],[0,1,2,3,4]),
 wordFill:wordFill("Every Obstacle Presents an Opportunity",[
  "In ancient times, a king had a boulder "," on a roadway. He hid himself and watched to see whether anyone would "," the huge rock. Wealthy merchants and courtiers walked around it. Many "," blamed the king, but no one acted.\n\nA peasant arrived carrying a "," of vegetables. He laid "," his burden and pushed the boulder aside. "," much effort, he succeeded. As he "," up his things, he saw a purse lying "," the rock had been. It "," gold coins and a note from the king. Every "," presents an opportunity to improve one's condition."
 ],["after","loudly","placed","down","contained","load","remove","obstacle","where","picked","beside","quietly"],[2,6,1,5,3,0,9,8,4,7],["placed on构成被动结构。","would后用动词原形remove。","loudly修饰blamed。","a load of表示一担/一批。","lay down表示放下。","after much effort表示经过许多努力。","picked up表示捡起、收拾。","where引导地点从句。","contained表示钱包里装有。","obstacle呼应开头的路障并点题。"]),
 wordForm:wordForm("What the Crack Made Possible",["The pot's "," (imperfect) caused a daily loss of water, but the bearer's "," (compassionate) changed the result. He made a "," (practice) plan and planted seeds along one side of the path. The pot still felt "," (misery) until it noticed the flowers. Their "," (beautiful) provided clear evidence of an unexpected contribution. The bearer's "," (explain) helped the pot understand that usefulness is not the same as "," (perfect). This new "," (perceive) did not remove the crack, but it reduced the pot's "," (ashamed) and encouraged a more "," (cheer) view of its daily journey."],["imperfection","compassion","practice","misery","beautiful","explain","perfect","perceive","ashamed","cheer"],["imperfection","compassion","practical","miserable","beauty","explanation","perfection","perception","shame","cheerful"]),
 essay:{prompt:"某英文网站正在征集题为“Turning a Weakness into Strength”的短文。请写一篇约80词的英文短文，内容包括：描述一个真实或设想的缺点；说明如何正视并改善它；写出它可能带来的新价值。",sample:"Everyone has weaknesses, but a weakness does not have to decide our whole value. I used to speak slowly in group discussions and felt ashamed of it. Then I began preparing two key points before each meeting and listening carefully while others spoke. My speed improved, and my careful listening helped me notice ideas that others missed. Like the cracked pot, I learned to improve what I could while using an imperfect quality in a positive way.",analysis:"预测类主题作文。三段要点齐全，呼应 Text A 的 flaw、ashamed、take notice of 和积极转化主题，约80词。"}
},
{
 id:2,unit:2,unitTitle:"A Path to Follow",title:"Unit 2 模拟卷二（教材精校版）",level:"语境运用",
 judgment:{title:"A Priceless Lesson in Humility",passage:humility,questions:[
  jq(1,"Morales was in Washington, D.C. for sightseeing.",0,"首段明确为 sightseeing trip。"),jq(2,"The elderly woman asked Morales for money.",1,"她要的是去邮局的方向。"),jq(3,"Morales looked carefully at the woman before giving her change.",1,"他没有看她便把零钱放进她手中。"),jq(4,"Morales realized that prejudice had shaped his response.",0,"第二段明确说明他凭偏见和假设判断她。"),jq(5,"The incident reawakened his belief in humility.",0,"教材原文直接说明这一点。"),jq(6,"Morales arrived in the United States alone.",1,"他和兄弟、姐妹以及母亲一同开始新生活。"),jq(7,"He had held several humble jobs before becoming an engineer.",0,"第三段列举了多种工作。"),jq(8,"The father at the restaurant praised Morales's hard work.",1,"那位父亲把像他一样当勤杂工当作负面警告。"),jq(9,"Morales's family later moved back to Honduras.",2,"文中没有提供这一信息。"),jq(10,"The woman reminded him to keep both his eyes and heart open.",0,"末段点明她带来的谦逊提醒。") ]},
 reading:{title:"The Jobs Behind an Engineer",passage:`When Felipe Morales described his path to becoming a network engineer, he did not begin with computers. He began with two suitcases and a family arriving from Honduras. At fifteen, he entered a new country with limited resources. His no-nonsense mother expected the children to work, learn and keep moving forward.

Morales washed dishes, repaired roofs, received money as a cashier, fixed machines and delivered pizzas. None of these jobs was his final goal, yet each required a skill that later mattered: accuracy, patience, responsibility or communication. He eventually became an engineer, but he refused to treat the earlier jobs as evidence that a worker had little value.

That belief was tested when he remembered being a seventeen-year-old busboy. A customer had pointed to him and warned a child not to end up like him. The remark reduced a whole person to a temporary job. Years later, Morales himself made a quick assumption about a blind woman in Washington. The two incidents were different, but both showed how easily a label can replace attention.

His career was an accomplishment, yet humility required him not to lose sight of the people and work that had shaped it.`,questions:[
  cq(11,"What did Morales's mother expect?",["Immediate wealth","Work and learning","A return to Honduras","Only computer study"],1,"首段说母亲要求孩子工作、学习并继续前进。"),cq(12,"Why are Morales's early jobs listed?",["To show they developed useful skills","To prove he disliked engineering","To compare salaries","To recommend one career"],0,"第二段说明每项工作都培养了后来有用的能力。"),cq(13,"What was wrong with the customer's remark?",["It was too quiet","It treated a temporary job as a person's whole value","It praised the busboy","It concerned computer skills"],1,"第三段指出这句话用暂时的工作标签概括了整个人。"),cq(14,"What connected the restaurant and Washington incidents?",["Both happened at age fifteen","Both involved loose change","Both showed quick labeling","Both ended at a post office"],2,"两件事都体现了未经了解便贴标签。"),cq(15,"What is the main message?",["Only professional work matters","Past work should be hidden","Achievement should remain connected with humility","Immigrants should avoid travel"],2,"末段强调成就不能让人忘记过去和谦逊。") ]},
 matching:matching("Keeping Eyes and Heart Open",[
  "Pause before acting on a reflex. A quick response may come from habit rather than from the facts of the present situation.","Look at the person and listen to the actual request. The blind woman needed directions, not loose change.","Compare assumptions with evidence. Ask what you truly know and what you have merely imagined about another person.","Remember experiences of being judged. Honest memory can reawaken compassion and prevent comfortable success from narrowing our view.","Repair the moment when possible. Morales guided the woman to the post office and accepted the lesson she offered."
 ],["Use memory to restore humility","Listen before deciding","Correct a mistaken response","Question unsupported beliefs","Interrupt an automatic reaction","Avoid all strangers"],[4,1,3,0,2],["create a moment for thought","hear what help is really needed","separate fact from prejudice","remain connected with one's past","take responsible action after an error","protect every first impression"],[0,1,2,3,4]),
 sentenceFill:insertion("From Assumption to Humility",[
  "Morales heard the words “Can you help me?” outside the Reagan Center. "," He interpreted the extended hand before he understood the request.\n\nThe woman refused the meaning he had placed on the moment. "," Her simple correction made his loose change feel like evidence of prejudice.\n\nThe shock reached beyond one embarrassing mistake. "," He remembered arriving as an immigrant and doing many humble jobs.\n\nThose memories made his assumption harder to excuse. "," He had witnessed similar judgments against himself, family members and friends.\n\nThe incident therefore became a path rather than only a failure. "," It reaffirmed a core belief and led him to keep his eyes and heart open."
 ],["In a natural reflex, he assumed the blind woman was a panhandler.","She explained that she only wanted help finding the post office.","It reawakened parts of his own history that comfort had hidden.","He knew from experience what unfair labeling felt like.","By reflecting and helping her, he recovered the humility he valued.","She asked him to buy a ticket for a sightseeing tour."],[0,1,2,3,4]),
 wordFill:wordFill("Vocabulary from A Priceless Lesson",["The Washington "," began when an elderly woman "," her hand. Morales reacted before listening and made an assumption based on ",". Her correction gave him a "," lesson. It "," his memory of arriving as an immigrant and doing "," jobs. He had personally "," unfair treatment, yet comfortable life had hidden that "," belief. The woman became an unexpected "," in his life, and her words helped him "," his commitment to humility."],["incident","priceless","extended","core","humble","reawakened","witnessed","treasure","reaffirm","prejudice","reflex","eventually"],[0,2,9,1,5,4,6,3,7,8],["incident作主语。","extended her hand为教材搭配。","prejudice说明无事实依据的偏见。","priceless lesson为原文核心表达。","reawakened表示重新唤起。","humble jobs为原文搭配。","witnessed表示亲眼见过。","core belief为核心信念。","treasure比喻珍贵的提醒。","reaffirm表示重新确认。"]),
 wordForm:wordForm("A Moment of Self-Examination",["Morales's "," (assume) was immediate but wrong. His "," (annoy) disappeared when the woman explained her need. The "," (incident) lesson was not about money but about "," (humble). His earlier experience as an "," (immigrate) should have made him more alert to unfair judgment. He had "," (eventual) achieved professional success after years of work, but success had made "," (forget) easier. The woman's words caused a sudden "," (realize), renewed his "," (believe) in treating people fairly and encouraged more "," (compassion) behavior."],["assume","annoy","incident","humble","immigrate","eventual","forget","realize","believe","compassion"],["assumption","annoyance","incidental","humility","immigrant","eventually","forgetfulness","realization","belief","compassionate"]),
 essay:{prompt:"学校将举行英语演讲比赛。请按照 Unit 2 Practical Writing 的 Notice 格式，写一则约80词的英文通知，必须包含：比赛时间（6月14日星期四上午9点）；地点（Student Hall）；活动内容、报名方式和发布单位。",sample:"NOTICE\n\nAn English Speaking Contest will be held at 9:00 a.m. on Thursday, June 14, in the Student Hall. The topic is “A Priceless Lesson I Have Learned.” Students who wish to take part should register with their class monitor before June 8 and prepare a three-minute speech. Everyone is welcome to attend and support the speakers.\n\nEnglish Club",analysis:"本套直接落实教材 Practical Writing：Notice。范文含标题、时间、地点、活动、报名信息和发布单位，覆盖教材强调的 Time、Place、Activity。"}
},
{
 id:3,unit:2,unitTitle:"A Path to Follow",title:"Unit 2 模拟卷三（教材精校版）",level:"综合提升",
 judgment:{title:"The Boulder on the Road",passage:`An ancient king wanted to know how people responded to difficulty. He placed a huge boulder in a roadway and watched from a hidden position. Wealthy merchants and courtiers came first. They walked around the stone and loudly blamed the king for failing to keep the road clear. Although they complained about the obstacle, none tried to remove it.

Later, a peasant approached with a load of vegetables. He put down his burden and began pushing the boulder. The work was slow. After much effort, he finally moved the stone to the side of the road. When he picked up his vegetables, he noticed a purse where the boulder had been.

The purse contained gold coins and a note. The king explained that the gold belonged to the person who removed the obstacle. The peasant had not known a reward was waiting. He acted because the road needed to be cleared, and his action created a benefit for everyone who came after him.

The story's final sentence says that every obstacle presents an opportunity to improve one's condition. This does not mean that every difficulty hides money. The opportunity may be the chance to act responsibly, build strength or help others. The merchants saw only inconvenience and blame. The peasant saw work that could be done. His path changed when he stopped walking around the problem.` ,questions:[
  jq(1,"The king placed a boulder in the roadway.",0,"首段明确说明。"),jq(2,"The merchants tried together to move the rock.",1,"他们绕行并抱怨，没有行动。"),jq(3,"The peasant was carrying vegetables.",0,"第二段明确说明。"),jq(4,"The peasant moved the boulder without effort.",1,"文中说 after much effort。"),jq(5,"A purse lay where the boulder had been.",0,"第二段末明确说明。"),jq(6,"The purse contained silver coins.",1,"里面是 gold coins。"),jq(7,"The peasant knew about the reward in advance.",1,"他行动时并不知道有奖励。"),jq(8,"Removing the stone helped later travelers.",0,"第三段说明道路被清理，后来者受益。"),jq(9,"The king later made the peasant a courtier.",2,"文中未提及。"),jq(10,"An obstacle may offer a chance for responsible action.",0,"末段对寓意作出这一解释。") ]},
 reading:{title:"When University Excitement Wears Off",passage:`When students first enter university, they are often eager to explore a new environment and make friends. As time goes by, however, the excitement may wear off. Lectures can seem ordinary, food becomes easy to complain about, and a student may begin to believe that university life has failed to meet every expectation.

This change is not proof that the student chose the wrong path. Familiarity naturally removes some novelty. The more useful question is how to respond when the new becomes routine. One student may list every imperfection and grow miserable. Another may take notice of opportunities that were invisible during the busy first weeks: a study group, a volunteer project, a conversation with a teacher or a skill that needs patient practice.

A sensible plan begins with one honest problem. If loneliness is the issue, the student can join a regular activity instead of waiting for friendship to happen. If lectures are difficult, the student can prepare questions and visit office hours. Small actions do not create a perfect university, but they turn disappointment into information.

The goal is not to force cheerful feelings. It is to accept an imperfect experience, improve what can be changed and make full use of what remains available.`,questions:[
  cq(11,"What often happens after the first excitement?",["Students leave immediately","Familiarity makes university seem ordinary","All lectures end","Food improves"],1,"第一段说新鲜感会逐渐消退。"),cq(12,"What is a more useful question?",["How to respond to routine","How to avoid every lecture","How to become perfect","How to change the university name"],0,"第二段明确提出应考虑如何回应日常化。"),cq(13,"Which action addresses loneliness?",["Complaining about food","Waiting silently","Joining a regular activity","Leaving all groups"],2,"第三段直接给出该建议。"),cq(14,"What do small actions turn disappointment into?",["Money","Information","Pride","Prejudice"],1,"第三段末明确说明。"),cq(15,"What does the writer recommend?",["Pretending everything is perfect","Combining acceptance with practical improvement","Keeping every expectation unchanged","Ignoring available opportunities"],1,"末段总结为接受不完美、改善可改善之处并利用现有机会。") ]},
 matching:matching("From Complaints to Constructive Action",[
  "Notice the moment when disappointment begins to replace curiosity. Naming the change prevents a temporary mood from becoming a final judgment.","Separate facts from expectations. A lecture may be demanding without being useless, and an ordinary meal is not proof that the whole experience has failed.","Choose one obstacle rather than attacking everything at once. A specific problem makes a specific response possible.","Use resources already beside the path. Teachers, classmates, clubs and quiet study spaces may be available before a student takes notice of them.","Review the result and adjust. Progress may mean improved participation or a stronger routine, not the creation of a perfect campus."
 ],["Use existing opportunities","Define one workable problem","Observe and revise","Recognize declining enthusiasm","Test expectations against facts","Leave at the first difficulty"],[3,4,1,0,2],["identify a change in attitude","avoid exaggerating one weakness","select a manageable target","take advantage of nearby support","measure realistic improvement","demand a flawless experience"],[0,1,2,3,4]),
 sentenceFill:insertion("Happiness Is Not Always Later",[
  "People often convince themselves that life will be better after the next stage. "," They wait for marriage, children, a nicer car, a vacation or retirement.\n\nEach hoped-for stage soon produces another condition. "," Contentment is postponed again because the present remains imperfect.\n\nThe problem is not the wish to improve life. "," The problem is losing sight of the life that is already happening.\n\nA better path combines plans with attention. "," We can work toward change while taking notice of people and opportunities around us now.\n\nThere is no perfect future that removes every frustration. "," If happiness is never possible in an unfinished present, it may never arrive at all."
 ],["The imagined finish line keeps moving.","Then they become frustrated that reality does not match the picture.","Goals can guide responsible action.","Present attention does not require giving up future goals.","The truth is that right now is the only time in which we can act.","Every adult receives the same house and car."],[1,0,2,3,4]),
 wordFill:wordFill("Taking Notice of the Present",["A student may feel "," when the excitement of university wears off. Instead of treating every "," as proof of failure, the student can show "," toward personal limits and examine the situation. A difficult course may contain a hidden "," for growth. Useful support is often available, but learners must take "," of it. They can "," a study plan, ask for help and complete a realistic "," of work each day. Honest reflection may change their "," of university life. A "," routine is not perfect, but it can still "," a learner's experience."],["miserable","imperfection","compassion","opportunity","advantage","accomplish","portion","perception","practical","transform","decorate","reply"],[0,1,2,3,4,5,6,7,8,9],["feel后用miserable。","every后接imperfection。","show compassion toward表示体谅。","hidden opportunity表示隐藏机会。","take advantage of为教材短语。","can后用accomplish。","a portion of表示一定量。","perception表示看法。","practical修饰routine。","transform表示改变。"]),
 wordForm:wordForm("Learning from an Obstacle",["The peasant's "," (decide) to act separated him from the complainers. Their "," (loud) expressed blame but produced no change. Moving the stone required "," (strong) and patient effort. His action was both "," (practice) and helpful. The "," (discover) of the purse was unexpected, but the deeper reward was an "," (improve) in the road for everyone. The king's test revealed the "," (different) between complaint and responsibility. The story encourages "," (construct) action, a "," (will) response to difficulty and greater "," (aware) of opportunities hidden inside obstacles."],["decide","loud","strong","practice","discover","improve","different","construct","will","aware"],["decision","loudness","strength","practical","discovery","improvement","difference","constructive","willing","awareness"]),
 essay:{prompt:"某英文学习平台正在征集题为“An Obstacle Can Be an Opportunity”的短文。请写一篇约80词的英文短文，内容包括：描述遇到的一个障碍；说明你的具体行动；写出从中获得的机会或成长。",sample:"Last term, I had to give a presentation, but I was afraid of speaking in public. Instead of walking around the obstacle, I divided the task into small steps. I wrote a clear outline, practised before a mirror and asked a friend for feedback. My speech was not perfect, yet I completed it calmly. The obstacle gave me an opportunity to improve my communication skills and showed me that action is more useful than complaint.",analysis:"预测类记叙作文，以教材路障故事为迁移依据，要求事件、行动、收获三项完整。"}
},
{
 id:4,unit:2,unitTitle:"A Path to Follow",title:"Unit 2 模拟卷四（教材精校版）",level:"全真模拟",
 judgment:{title:"Accepting a Thank-You",passage:`For years, a volunteer named Rosa had difficulty accepting compliments. When someone thanked her for arranging a meal or helping with a form, she would look away and mumble, “It was nothing.” She believed this response showed humility. Praise made her uncomfortable, and refusing it seemed safer than appearing proud.

One day a friend thanked Rosa for driving him to several medical appointments. As usual, she tried to dismiss the help. The friend replied that he needed to say thank you. Accepting his words gracefully would give him a chance to recognize the care he had received. By refusing every expression of gratitude, Rosa was not only controlling her own discomfort; she was also preventing another person from completing an honest exchange.

The idea surprised her. She realized that humility did not require denying every accomplishment. A person could recognize a contribution without claiming to be better than others. After that, Rosa practised a simple reply: “Thank you. I am glad I could help.” At first the words felt unnatural, but they gradually became easier.

Rosa still tried to avoid pride. Yet she no longer confused humility with making herself invisible. A sincere thank-you could be accepted as a gift rather than treated as a dangerous judgment. Giving and receiving respect were two parts of the same human conversation.` ,questions:[
  jq(1,"Rosa used to reject compliments.",0,"首段明确说明。"),jq(2,"She believed saying “It was nothing” showed humility.",0,"首段说明她过去的理解。"),jq(3,"Her friend thanked her for lending him money.",1,"他感谢她开车带他看病。"),jq(4,"The friend wanted a chance to recognize her care.",0,"第二段直接说明。"),jq(5,"Rosa immediately found the new reply natural.",1,"起初觉得不自然，后来才逐渐容易。"),jq(6,"Rosa decided that pride was always good.",1,"她仍努力避免骄傲。"),jq(7,"The passage gives the name of Rosa's volunteer organization.",2,"文中未给出组织名称。"),jq(8,"Rosa learned that humility need not deny every accomplishment.",0,"第三段点明。"),jq(9,"She practised a short and graceful response.",0,"文中给出她练习的具体回应。"),jq(10,"The passage treats respect as something people both give and receive.",0,"末句总结了双向尊重。") ]},
 reading:{title:"A Positive Attitude and an Open Heart",passage:`A positive attitude helps people cope with everyday life, but it is often misunderstood. It does not mean calling every event good. A cracked pot still loses water, prejudice still hurts people, and an obstacle may demand real effort. Optimism begins by seeing the whole situation rather than only its darkest part.

This wider view makes constructive change easier. The water bearer recognized a flaw and created a useful purpose for the leaking water. Morales recognized prejudice in his own reflex and corrected his behavior. Neither person waited for a perfect feeling. Each faced an uncomfortable fact and chose a responsible response.

Positive thinking becomes dangerous when it silences pain or excuses harm. Telling an unfortunate person simply to “cheer up” may show little compassion. A better response listens first, checks assumptions and asks what practical help is needed. Hope then grows from attention and action, not from an empty slogan.

An open heart therefore needs an open mind. People should expect improvement while remaining willing to learn from evidence. This state of mind is worth developing because it allows weakness, responsibility and possibility to be considered together.`,questions:[
  cq(11,"What does a positive attitude NOT require?",["Calling every event good","Seeing the whole situation","Taking responsible action","Learning from evidence"],0,"首段明确否定把每件事都说成好事。"),cq(12,"What do the water bearer and Morales share?",["They hide every flaw","They face facts and respond","They receive gold","They avoid responsibility"],1,"第二段比较二者都正视事实并采取行动。"),cq(13,"When can positive thinking be dangerous?",["When it supports change","When it silences pain or excuses harm","When it checks assumptions","When it includes compassion"],1,"第三段直接说明。"),cq(14,"What should come before practical help?",["A quick label","Listening and checking assumptions","A cheerful slogan","A reward"],1,"第三段建议先倾听、核查假设。"),cq(15,"What is the best title?",["How to Deny Every Weakness","Optimism Joined with Responsibility","Why Evidence Is Unnecessary","The Price of Sightseeing"],1,"全文主题是有责任、有事实依据的积极态度。") ]},
 matching:matching("Humility in Everyday Decisions",[
  "Receiving praise can require humility. A graceful thank-you accepts another person's honest judgment without turning it into a claim of superiority.","Offering help requires attention. Before acting, listen to what is actually needed instead of assuming that age, disability or appearance gives the answer.","Admitting an error protects core values. Morales did not defend his reflex; he allowed the incident to reawaken a better principle.","Recognizing an accomplishment can remain modest. The goal is accurate self-understanding, not making every contribution invisible.","Keeping an open heart is a continuing practice. Comfort and success can make anyone lose sight of earlier lessons, so reflection must be renewed."
 ],["Stay alert after success","Accept gratitude gracefully","Let mistakes restore principles","Listen before helping","Acknowledge work without superiority","Refuse every compliment"],[1,3,2,4,0],["complete a respectful exchange","discover the real request","learn rather than defend oneself","describe a contribution accurately","reaffirm humility over time","assume labels are facts"],[0,1,2,3,4]),
 sentenceFill:insertion("A Notice That People Can Use",[
  "A useful notice begins with a clear activity. "," Readers should understand immediately what is going to happen.\n\nTime must be complete rather than vague. "," A date, day of the week and hour prevent different assumptions.\n\nPlace is equally important. "," A building name may need a room number or another practical detail.\n\nExtra instructions should serve the activity. "," Registration, materials or a contact person may be included when readers need them.\n\nFinally, the notice should remain concise and easy to see. "," Simple organization shows respect for the reader's time."
 ],["Its title and opening line should name the event.","For example, “Thursday, June 14, at 9:00 a.m.” is specific.","“At school” may not tell participants where to gather.","They should not bury the three essential parts under unrelated explanation.","Time, place and activity form the essential information.","Every notice must include the writer's life story."],[0,1,2,3,4]),
 wordFill:wordFill("Choosing a Constructive Attitude",["A positive attitude helps people "," with ordinary difficulty. It encourages "," without pretending that every problem is pleasant. When an "," occurs, a thoughtful person avoids an immediate "," about who is responsible. Careful attention may "," a forgotten value and reveal a more "," response. People who have experienced "," treatment should not lose "," of that history after success. Their past can become a "," rather than a burden and can help them keep their "," beliefs alive."],["cope","optimism","incident","assumption","reawaken","constructive","unfair","sight","treasure","core","loose","eventually"],[0,1,2,3,4,5,6,7,8,9],["cope with为固定搭配。","optimism作encourages的宾语。","incident表示发生的事情。","assumption表示无证据的判断。","reawaken表示重新唤起。","constructive修饰response。","unfair修饰treatment。","lose sight of为教材短语。","treasure比喻珍贵经验。","core beliefs为核心信念。"]),
 wordForm:wordForm("An Open and Responsible Mind",["A genuinely "," (positivity) attitude begins with accurate observation. It makes "," (construct) change possible and reduces "," (necessary) worry without denying pain. A person should respond "," (compassion) to those in difficulty and remain "," (will) to question first impressions. Such "," (humble) prevents quick labels from becoming fixed prejudice. Regular "," (reflect) can renew core values, while practical "," (act) turns hope into evidence. The result is not "," (perfect), but a deeper "," (understand) of oneself and others."],["positivity","construct","necessary","compassion","will","humble","reflect","act","perfect","understand"],["positive","constructive","unnecessary","compassionately","willing","humility","reflection","action","perfection","understanding"]),
 essay:{prompt:"假设你是班长，请为一次“Keep Your Eyes and Heart Open”校园志愿活动写一则约80词的英文通知。内容包括：活动时间和集合地点；帮助对象与主要活动；报名截止时间及联系人。",sample:"NOTICE\n\nA campus volunteer activity named “Keep Your Eyes and Heart Open” will take place this Saturday from 9:00 to 11:30 a.m. Please meet at the school gate at 8:45. We will visit elderly residents, help with simple housework and listen to their stories. Students who want to join should give their names to Li Hua before Thursday afternoon. Please wear comfortable shoes.\n\nClass Committee",analysis:"预测 Notice 题。沿用教材实用写作体裁，但活动、时间、地点和任务均与第二套不同，避免作文材料重复。"}
}
];

export function reviseUnit2Papers(legacy:Paper[]):Paper[]{
 return paperData.map((paper,i)=>{
  const coverage=legacy[i]?.coverage;
  const audit=[...(coverage?.vocabulary??[]),...(coverage?.phrases??[]),...(coverage?.textFacts??[]),...(coverage?.exerciseFocus??[])].join("；");
  return {...paper,coverage,essay:{...paper.essay,analysis:`${paper.essay.analysis} 教材覆盖核对：${audit}`}};
 });
}
