import {buildUnitPapers,type UnitPlan} from "./paper-generator";

export const unitPlans:UnitPlan[]=[
{
 unit:2,title:"A Path to Follow",textA:"Cracked or Perfect: We Can Make a Difference!",textB:"A Reminder of Humility",
 verbs:["recognize","transform","reconsider","appreciate"],nouns:["imperfection","compassion","prejudice","opportunity","humility"],adjectives:["ashamed","valuable","unfortunate"],
 forms:[["value","valuable"],["humble","humbly"],["reflect","reflection"],["practice","practical"],["responsible","responsibility"],["confident","confidence"],["expect","unexpected"],["determine","determination"],["compassion","compassionate"],["understand","understanding"]],
 phrases:["take advantage of","take notice of","feel sorry for","lose sight of"],
 scenarios:[
  {title:"The Leaking Water Bottle",person:"Mei",setting:"a school garden",challenge:"a damaged bottle seemed useful only for carrying half its water",action:"Mei placed herb seeds along the route and used the drops to water them",outcome:"the path became greener and the class stopped calling the bottle useless",insight:"an imperfection can become valuable when it is understood and used with imagination",evidence:"After three weeks, plants grew only beside the route where the bottle had leaked",essay:"Finding Value in an Imperfection"},
  {title:"A Pause Before Judgment",person:"Daniel",setting:"a crowded railway station",challenge:"he assumed that an elderly stranger asking for help wanted money",action:"Daniel listened before reacting and learned that the stranger only needed directions",outcome:"he apologized and later examined how quickly prejudice had shaped his response",insight:"humility begins when we question unsupported assumptions about other people",evidence:"His written account compared what he had imagined with what the stranger had actually said",essay:"Why We Should Think Before We Judge"},
  {title:"The Quiet Team Member",person:"Aisha",setting:"a community design workshop",challenge:"one participant spoke slowly and was repeatedly ignored",action:"Aisha invited him to explain his sketch and gave the group time to ask respectful questions",outcome:"his low-cost design solved a problem that the louder proposals had missed",insight:"taking notice of overlooked people can reveal strengths hidden by first impressions",evidence:"The final model used three features taken directly from his original sketch",essay:"Listening to an Overlooked Voice"},
  {title:"Flowers Along the Alley",person:"Luis",setting:"an apartment neighbourhood",challenge:"rainwater escaped through a cracked drainpipe and left the alley muddy",action:"Luis guided the water into planters built from reused containers",outcome:"neighbours turned a recurring nuisance into a shared garden",insight:"a path gains meaning when people respond to flaws with compassion and purposeful action",evidence:"Water use fell while twelve planters survived the dry part of the month",essay:"Turning a Problem into a Possibility"}
 ]
},
{
 unit:3,title:"Green Transportation",textA:"Bus Chick's Manifesto",textB:"Bike to Work: Reasons You Should Try",
 verbs:["reduce","protect","encourage","replace"],nouns:["commute","pollution","transportation","incentive","camaraderie"],adjectives:["practical","vibrant","sustainable"],
 forms:[["environment","environmental"],["caution","cautiously"],["observe","observation"],["practice","practical"],["responsible","responsibility"],["motivate","motivation"],["expect","unexpected"],["persist","persistence"],["sustainability","sustainable"],["aware","awareness"]],
 phrases:["on demand","except for","bear in mind","make sense"],
 scenarios:[
  {title:"One Bus Day Each Week",person:"Rina",setting:"a software company outside the city",challenge:"most employees drove alone even when their schedules matched",action:"Rina organized a weekly bus day and shared clear route information",outcome:"participants discovered that commuting together reduced stress as well as car use",insight:"public transport becomes attractive when environmental purpose is joined with practical support",evidence:"The first eight participants avoided thirty-two individual car journeys in one month",essay:"Making Public Transport a Real Choice"},
  {title:"The Safe Cycling Route",person:"Owen",setting:"a suburban secondary school",challenge:"students wanted to cycle but feared a dangerous road junction",action:"Owen mapped a quieter route and asked the council for a protected crossing",outcome:"more families allowed students to travel by bicycle",insight:"green choices require safe design rather than moral pressure alone",evidence:"Cycle-rack use rose from nine bicycles to twenty-seven after the crossing opened",essay:"How to Make Cycling Safer"},
  {title:"A Car-Free Market Morning",person:"Nadia",setting:"a busy town centre",challenge:"weekend traffic made the market noisy and polluted",action:"Nadia proposed closing two streets to cars for one Saturday morning",outcome:"walking, cycling and bus travel increased while shop sales remained steady",insight:"temporary experiments can help a community test a greener transport idea",evidence:"Air-quality monitors recorded fewer roadside particles during the trial",essay:"A Car-Free Day in My Community"},
  {title:"Rewards for a Cleaner Commute",person:"Haruto",setting:"a regional hospital",challenge:"shift workers believed cars were their only reliable option",action:"Haruto arranged secure bicycle storage, bus discounts and a ride-sharing board",outcome:"workers chose different low-carbon methods suited to their shifts",insight:"well-designed incentives can turn environmental awareness into lasting behaviour",evidence:"A staff survey showed that single-person car trips fell for six consecutive weeks",essay:"Encouraging a Greener Journey to Work"}
 ]
},
{
 unit:4,title:"Friends and Friendship",textA:"The Best Kind of Friend",textB:"The Colors of Friendship",
 verbs:["support","appreciate","represent","resolve"],nouns:["friendship","loyalty","reflection","difference","harmony"],adjectives:["lifelong","precious","unique"],
 forms:[["friend","friendly"],["quiet","quietly"],["reflect","reflection"],["construct","constructive"],["responsible","responsibility"],["confident","confidence"],["expect","unexpected"],["determine","determination"],["respect","respectful"],["appreciate","appreciation"]],
 phrases:["stand by","blow one's own trumpet","be willing to","in the midst of"],
 scenarios:[
  {title:"The Honest Rehearsal Partner",person:"Sofia",setting:"a school music club",challenge:"her closest friend wanted praise for a performance that still needed work",action:"Sofia first recognized the effort and then offered two specific suggestions",outcome:"the friend improved the performance without feeling personally rejected",insight:"a true friend combines loyalty with honest and considerate feedback",evidence:"The second rehearsal corrected both problems that Sofia had identified",essay:"Honesty in Friendship"},
  {title:"Seven Colors, One Mural",person:"Malik",setting:"a neighbourhood art project",challenge:"each volunteer insisted that one colour should dominate the wall",action:"Malik asked everyone to explain what their colour represented before designing a shared pattern",outcome:"the finished mural depended on contrast and balance rather than superiority",insight:"differences strengthen friendship when each person is appreciated as unique",evidence:"Every volunteer's colour appeared in a section connected to the common centre",essay:"Why Differences Can Strengthen a Team"},
  {title:"Standing By a New Student",person:"Grace",setting:"a university language class",challenge:"a new student was isolated because he made frequent speaking errors",action:"Grace invited him into her study group and gave him time to finish his ideas",outcome:"he became an active member and later helped others with mathematics",insight:"friendship is shown through patient action when someone feels excluded",evidence:"His participation record changed from one comment a week to several contributions each lesson",essay:"Helping Someone Feel Included"},
  {title:"Repairing a Broken Promise",person:"Ethan",setting:"a volunteer team",challenge:"he forgot an important task and blamed his friend during a stressful meeting",action:"Ethan admitted his mistake, apologized without excuses and completed the delayed work",outcome:"the friends rebuilt trust through clear expectations and consistent behaviour",insight:"conflict need not end a friendship when responsibility replaces pride",evidence:"For the next month, both friends used a shared checklist and missed no deadlines",essay:"How to Rebuild Trust"}
 ]
},
{
 unit:5,title:"Music and Leisure",textA:"Music as a Universal Language",textB:"Why We Need Vacations",
 verbs:["evoke","soothe","motivate","restore"],nouns:["melody","creativity","relaxation","routine","perspective"],adjectives:["universal","productive","recreational"],
 forms:[["music","musical"],["natural","naturally"],["imagine","imagination"],["practice","practical"],["responsible","responsibility"],["create","creativity"],["expect","unexpected"],["motivate","motivation"],["recreation","recreational"],["relax","relaxation"]],
 phrases:["relate to","look forward to","make a difference","over time"],
 scenarios:[
  {title:"A Song Without Shared Words",person:"Elena",setting:"an international youth camp",challenge:"participants spoke several languages and avoided conversation",action:"Elena asked each group to teach a simple rhythm and explain one favourite song",outcome:"music became an icebreaker that led to conversations beyond the activity",insight:"melody and rhythm can create connection even before people share fluent language",evidence:"By the final evening, every group performed a piece combining elements from three traditions",essay:"Music as a Bridge Between People"},
  {title:"The Ten-Minute Listening Break",person:"Marcus",setting:"a demanding office",challenge:"afternoon tension reduced his concentration and patience",action:"Marcus spent ten minutes listening to calm instrumental music away from his screen",outcome:"he returned to work more focused without extending his working day",insight:"a short intentional leisure activity can restore energy and perspective",evidence:"His two-week log showed fewer unfinished afternoon tasks on listening days",essay:"A Small Break That Improves My Day"},
  {title:"Vacation Near Home",person:"Priya",setting:"her own city",challenge:"she needed rest but could not afford a distant holiday",action:"Priya planned three days without work messages and explored unfamiliar local places",outcome:"the change in routine gave her the mental distance she had expected from travel",insight:"the value of a vacation lies in renewed attention, not only in distance or expense",evidence:"After the break, she identified solutions to two problems that had previously felt endless",essay:"Why a Simple Vacation Still Matters"},
  {title:"A Weekend of Active Leisure",person:"Noah",setting:"a family household",challenge:"everyone spent free time separately in front of a screen",action:"Noah planned a walk, a shared meal and an evening music game",outcome:"family members relaxed while also paying more attention to one another",insight:"leisure becomes restorative when it includes choice, variety and genuine participation",evidence:"All four family members later requested that one shared activity become a weekly routine",essay:"Planning Meaningful Leisure Time"}
 ]
},
{
 unit:6,title:"Life Lessons",textA:"Keep Your Dream",textB:"Go for It!",
 verbs:["pursue","reconsider","attempt","persist"],nouns:["dream","determination","courage","effort","decision"],adjectives:["realistic","exhausted","incredible"],
 forms:[["courage","courageous"],["brave","bravely"],["decide","decision"],["realism","realistic"],["responsible","responsibility"],["determine","determination"],["expect","unexpected"],["persist","persistence"],["purpose","purposeful"],["achieve","achievement"]],
 phrases:["as a result","in detail","come across","go for it"],
 scenarios:[
  {title:"Keeping the Design Dream",person:"Leo",setting:"a senior school classroom",challenge:"a teacher called his plan for an accessible playground unrealistic",action:"Leo kept the goal but researched costs and rewrote the plan with practical stages",outcome:"the revised design won support from a local community group",insight:"protecting a dream does not prevent us from improving the path toward it",evidence:"His new proposal included a budget, measurements and a six-month timetable",essay:"Keep the Dream, Improve the Plan"},
  {title:"Finishing the First Race",person:"Amara",setting:"a community swimming event",challenge:"she was far slower than the experienced competitors",action:"Amara concentrated on completing each length safely instead of comparing positions",outcome:"spectators changed from quiet doubt to enthusiastic encouragement",insight:"courage can be measured by wholehearted effort rather than by a medal",evidence:"She completed the full distance after having learned to swim only ten months earlier",essay:"What It Really Means to Win"},
  {title:"A Second Attempt at the Workshop",person:"Ben",setting:"a youth robotics workshop",challenge:"his first machine failed during a public demonstration",action:"Ben recorded the failure, asked for advice and rebuilt one mechanism at a time",outcome:"the next version completed the task and taught the team how to respond to setbacks",insight:"determination is most useful when it is joined with reflection and revision",evidence:"The repair notes identified three separate causes rather than blaming one general mistake",essay:"Learning from an Unsuccessful Attempt"},
  {title:"The Long Scholarship Application",person:"Yuki",setting:"a rural secondary school",challenge:"the application required experience and documents that seemed beyond her reach",action:"Yuki divided the work into weekly goals and sought help from teachers and former applicants",outcome:"she submitted a complete application and gained confidence regardless of the final decision",insight:"a large dream becomes realistic through detailed planning and persistent action",evidence:"Her checklist showed twenty-two completed steps across eight weeks",essay:"Turning a Dream into a Plan"}
 ]
},
{
 unit:7,title:"Attitude Is Altitude",textA:"A Motivator",textB:"Attitude Is Everything",
 verbs:["choose","reflect","encourage","overcome"],nouns:["attitude","mood","choice","motivation","setback"],adjectives:["positive","conscious","optimistic"],
 forms:[["positivity","positive"],["calm","calmly"],["reflect","reflection"],["practice","practical"],["responsible","responsibility"],["motivate","motivation"],["expect","unexpected"],["confident","confidence"],["construct","constructive"],["aware","awareness"]],
 phrases:["point out","lose touch","take action","be faced with"],
 scenarios:[
  {title:"Choosing a Response to Criticism",person:"Hana",setting:"a design office",challenge:"a client rejected weeks of work in one brief message",action:"Hana separated the useful criticism from the emotional tone and asked focused questions",outcome:"her team revised the design without allowing disappointment to control the project",insight:"a positive attitude is an active choice about response, not a denial of difficulty",evidence:"The revised proposal answered all four concerns listed by the client",essay:"Choosing My Response to a Difficult Situation"},
  {title:"The Recovery Notebook",person:"Sam",setting:"a rehabilitation centre",challenge:"slow progress after an injury made each exercise feel pointless",action:"Sam recorded one physical improvement and one encouraging thought every day",outcome:"he noticed progress that had been invisible when he judged himself only by perfect recovery",insight:"attention can be trained toward evidence of growth without ignoring pain",evidence:"After a month, his notes showed longer walking time and fewer abandoned sessions",essay:"How a Positive Record Can Help"},
  {title:"Changing the Team's Inner Dialogue",person:"Fatima",setting:"a student debate team",challenge:"three early defeats led members to call themselves hopeless",action:"Fatima replaced general complaints with specific questions about preparation and delivery",outcome:"the team recovered motivation and improved one skill before each contest",insight:"language used about ourselves can either support action or strengthen self-defeat",evidence:"Judges' scores rose in the exact areas selected for weekly practice",essay:"The Power of Encouraging Self-Talk"},
  {title:"A Calm Choice During an Emergency",person:"Victor",setting:"a crowded community event",challenge:"a sudden power failure caused confusion and frightened visitors",action:"Victor controlled his breathing, gave simple directions and listened to safety staff",outcome:"people left the hall in an orderly way and no one was injured",insight:"attitude influences action most clearly when circumstances cannot be immediately changed",evidence:"The hall was cleared within six minutes according to the event report",essay:"Staying Positive Does Not Mean Doing Nothing"}
 ]
},
{
 unit:8,title:"The Mystery of Life",textA:"Embracing the Mystery",textB:"Research Is a State of Mind",
 verbs:["embrace","question","investigate","discover"],nouns:["mystery","possibility","research","evidence","curiosity"],adjectives:["infinite","uncertain","systematic"],
 forms:[["mystery","mysterious"],["system","systematically"],["observe","observation"],["practice","practical"],["responsible","responsibility"],["curious","curiosity"],["expect","unexpected"],["patient","patience"],["science","scientific"],["understand","understanding"]],
 phrases:["incline toward","stand against","be worth the effort","rule out"],
 scenarios:[
  {title:"Questions Beside the Night Pond",person:"Iris",setting:"a school nature reserve",challenge:"the number of frogs changed greatly from one evening to another",action:"Iris recorded weather, water level and sound at the same time for six weeks",outcome:"the class discovered a pattern without pretending to explain every change",insight:"mystery invites careful attention when uncertainty is accepted rather than feared",evidence:"Frog calls were most frequent after warmer rainy days, though several exceptions remained",essay:"Why Mystery Can Encourage Learning"},
  {title:"Choosing a Useful Research Problem",person:"Omar",setting:"a university study group",challenge:"members proposed impressive topics that were too broad to investigate",action:"Omar asked who would benefit, what evidence was available and whether the question could be tested",outcome:"the group selected a smaller problem about food waste in one dining hall",insight:"research begins with a worthwhile and workable question, not with a complicated title",evidence:"The final question could be answered through one month of measurements and interviews",essay:"How to Choose a Research Question"},
  {title:"Light After a Difficult Year",person:"Clara",setting:"a neighbourhood support group",challenge:"members had experienced losses they could not fully explain or repair",action:"Clara created space for honest stories and small acts of help without offering easy answers",outcome:"the group learned to recognize suffering while remaining open to love and possibility",insight:"embracing life's mystery means facing darkness without inclining the heart entirely toward it",evidence:"Members organized weekly visits and continued them after the formal meetings ended",essay:"Finding Hope Without Easy Answers"},
  {title:"The Missing Seeds Investigation",person:"Jun",setting:"a community vegetable garden",challenge:"newly planted seeds disappeared from several beds",action:"Jun listed possible causes, protected sample areas and compared the results",outcome:"the gardeners ruled out poor seed quality and identified birds as the main cause",insight:"a research state of mind replaces confident guesses with testable explanations",evidence:"Covered beds produced seedlings while uncovered beds showed fresh bird tracks",essay:"Solving an Everyday Mystery Through Research"}
 ]
},
{
 unit:9,title:"Making Every Minute Count",textA:"The Most Exciting Thing Ever",textB:"Keeper of the Spring",
 verbs:["value","maintain","prioritize","savour"],nouns:["minute","routine","contribution","purpose","attention"],adjectives:["faithful","meaningful","efficient"],
 forms:[["meaning","meaningful"],["regular","regularly"],["observe","observation"],["practice","practical"],["responsible","responsibility"],["contribute","contribution"],["expect","unexpected"],["patient","patience"],["purpose","purposeful"],["appreciate","appreciation"]],
 phrases:["drop in on","make room for","clear away","take for granted"],
 scenarios:[
  {title:"The Last Thing Was the Best Thing",person:"Rose",setting:"a senior community centre",challenge:"a visitor expected an exciting life story to mean a famous achievement",action:"Rose described excitement as full attention to the person and task before her",outcome:"the visitor reconsidered the habit of postponing happiness until a major event",insight:"a minute becomes valuable when we are present rather than when it looks impressive",evidence:"During later visits, the visitor recorded ordinary conversations that had changed his day",essay:"Making an Ordinary Moment Count"},
  {title:"The Invisible Library Volunteer",person:"Kofi",setting:"a public library",challenge:"returned books accumulated because one quiet volunteer's work was taken for granted",action:"Kofi documented the daily sorting and shelving that kept materials available",outcome:"the library protected the role and trained two additional volunteers",insight:"small regular contributions may support an entire system even when they attract little attention",evidence:"When the task stopped for two days, more than six hundred books remained unavailable",essay:"Valuing Work That People Do Not Notice"},
  {title:"Three Priorities Before Breakfast",person:"Mina",setting:"a home study space",challenge:"messages and minor tasks consumed the time reserved for exam preparation",action:"Mina selected three priorities each evening and delayed notifications until one was complete",outcome:"she finished important work earlier and felt less pressure at night",insight:"making time count requires deliberate priorities, not simply moving faster",evidence:"Her weekly record showed five additional focused study periods without longer total hours",essay:"How I Protect Time for Important Work"},
  {title:"Clearing the Community Stream",person:"Adrian",setting:"a mountain village",challenge:"leaves and rubbish slowly blocked the spring that supplied clean water",action:"Adrian organized short weekly checks before the damage became obvious",outcome:"the flow remained clear and residents understood the value of preventive work",insight:"faithful maintenance protects resources that people notice only after they are lost",evidence:"Water tests stayed stable throughout the rainy season while a nearby untreated channel became cloudy",essay:"Why Regular Maintenance Matters"}
 ]
},
{
 unit:10,title:"Media - Blessing or Curse",textA:"Advertising to Children",textB:"The Illusion of Perfection",
 verbs:["influence","target","question","evaluate"],nouns:["advertising","audience","illusion","standard","media"],adjectives:["naive","misleading","commercial"],
 forms:[["media","media-related"],["critical","critically"],["analyze","analysis"],["practice","practical"],["responsible","responsibility"],["confident","confidence"],["expect","unexpected"],["aware","awareness"],["ethics","ethical"],["perfect","perfection"]],
 phrases:["appeal to","be exposed to","compare with","have an effect on"],
 scenarios:[
  {title:"The Cartoon Cereal Test",person:"Lily",setting:"a primary school media lesson",challenge:"children preferred a cereal after seeing its animated character",action:"Lily showed the same cereal in plain packaging and compared the reactions",outcome:"students recognized that the character had influenced desire rather than taste",insight:"young audiences need help separating product information from emotional advertising",evidence:"Most students changed their ratings when labels were hidden during a second tasting",essay:"Teaching Children to Understand Advertising"},
  {title:"One Photograph, Many Edits",person:"Maya",setting:"a teenage photography club",challenge:"members compared themselves with flawless images on social media",action:"Maya demonstrated lighting, posing and digital editing on one ordinary portrait",outcome:"the group became more critical of images presented as natural perfection",insight:"media literacy reveals the construction behind unrealistic standards",evidence:"The club produced six visibly different images from the same original photograph",essay:"The Truth Behind a Perfect Image"},
  {title:"Checking the Sponsored Review",person:"Theo",setting:"an online shopping group",challenge:"a popular video praised a product without clearly discussing payment",action:"Theo traced the sponsorship label and compared independent reviews",outcome:"the group delayed the purchase and created a checklist for commercial content",insight:"audiences should examine who benefits from a persuasive media message",evidence:"Three independent tests contradicted the video's main performance claim",essay:"How to Judge an Online Product Review"},
  {title:"A Week Without Targeted Ads",person:"Sara",setting:"a family household",challenge:"personalized advertisements repeatedly encouraged unnecessary purchases",action:"Sara changed privacy settings, recorded ad exposure and discussed each impulse before buying",outcome:"the family spent less and became aware of how targeting shaped attention",insight:"media can be useful, but responsible users must actively manage its commercial influence",evidence:"Unplanned purchases fell from seven in the previous week to one during the trial",essay:"Managing the Influence of Online Advertising"}
 ]
},
{
 unit:11,title:"Effective Communication",textA:"Active Listening",textB:"Effective Communication",
 verbs:["listen","convey","rephrase","clarify"],nouns:["message","barrier","feedback","tone","communication"],adjectives:["nonverbal","effective","verbal"],
 forms:[["effect","effective"],["patient","patiently"],["interpret","interpretation"],["practice","practical"],["responsible","responsibility"],["confident","confidence"],["expect","unexpected"],["clear","clarity"],["respect","respectful"],["understand","understanding"]],
 phrases:["be aware of","be responsible for","put aside","point of view"],
 scenarios:[
  {title:"Listening Before Giving Advice",person:"Nora",setting:"a university residence",challenge:"her roommate described a problem but felt ignored by quick solutions",action:"Nora put aside her advice, maintained attention and paraphrased what she heard",outcome:"the roommate corrected one misunderstanding and explained the real concern",insight:"active listening seeks accurate understanding before response",evidence:"Nora's summary changed after the roommate clarified two important details",essay:"Why Listening Comes Before Advice"},
  {title:"The Missing Deadline Message",person:"Caleb",setting:"a project workplace",challenge:"an unclear email left two teams with different ideas about a deadline",action:"Caleb replaced vague wording with a date, assigned responsibilities and requested confirmation",outcome:"both teams completed the next stage without another scheduling conflict",insight:"effective communication requires the sender to make meaning checkable",evidence:"Every recipient repeated the same date and task in the follow-up message",essay:"Writing a Clear Workplace Message"},
  {title:"Reading the Silent Signals",person:"Amina",setting:"a parent-teacher meeting",challenge:"spoken agreement did not match a parent's tense posture and worried expression",action:"Amina noticed the nonverbal signals and invited the parent to explain remaining concerns",outcome:"they identified a practical obstacle that polite words had hidden",insight:"tone, expression and manner can add critical information to verbal language",evidence:"The parent relaxed only after transport arrangements were included in the plan",essay:"What Nonverbal Communication Can Tell Us"},
  {title:"Paraphrasing Across Departments",person:"Ken",setting:"a hospital planning meeting",challenge:"technical words carried different meanings for medical and administrative staff",action:"Ken asked each side to rephrase key terms and give concrete examples",outcome:"the group discovered disagreement in definitions rather than in the shared goal",insight:"paraphrasing reduces barriers when familiar words hide different interpretations",evidence:"A revised glossary removed five ambiguous terms from the final plan",essay:"Using Paraphrasing to Prevent Misunderstanding"}
 ]
},
{
 unit:12,title:"Technology: A Double-Edged Sword",textA:"Privacy in Our High-Tech Society",textB:"Worse Living Through Better Technology",
 verbs:["monitor","protect","control","balance"],nouns:["privacy","technology","surveillance","profile","cyberspace"],adjectives:["transparent","electronic","ubiquitous"],
 forms:[["technology","technological"],["care","carefully"],["observe","observation"],["practice","practical"],["responsible","responsibility"],["private","privacy"],["expect","unexpected"],["aware","awareness"],["ethics","ethical"],["understand","understanding"]],
 phrases:["or rather","in addition to","be caught up in","put on hold"],
 scenarios:[
  {title:"The Fitness App Privacy Check",person:"Zoe",setting:"a workplace wellness program",challenge:"an app requested location, contacts and health information beyond its main purpose",action:"Zoe reviewed permissions and shared only the data required for step counting",outcome:"colleagues gained the benefit without automatically exposing complete personal profiles",insight:"convenient technology should not make unlimited surveillance seem normal",evidence:"The app continued its core function after five optional permissions were refused",essay:"Protecting Privacy While Using an App"},
  {title:"Dinner Without Notifications",person:"Rafael",setting:"a family dining room",challenge:"phones repeatedly interrupted conversation and divided attention",action:"Rafael proposed placing devices in a box for thirty minutes during dinner",outcome:"family members talked longer and remembered more of one another's news",insight:"technology serves relationships best when people control when it receives attention",evidence:"In a two-week trial, interruptions fell from an average of nine per meal to fewer than one",essay:"Creating a Healthy Boundary for Technology"},
  {title:"Understanding a Recommendation Feed",person:"Mei",setting:"a secondary school digital-literacy class",challenge:"students assumed that a video feed represented the world objectively",action:"Mei created two new accounts with different viewing histories and compared recommendations",outcome:"students saw how electronic profiles shaped what appeared on each screen",insight:"personalized technology can narrow perception unless users seek information beyond the feed",evidence:"After one hour, the two accounts displayed almost entirely different topics",essay:"Why We Should Look Beyond an Algorithmic Feed"},
  {title:"The Smart Camera Decision",person:"Jonas",setting:"an apartment building",challenge:"residents wanted security cameras but disagreed about constant monitoring",action:"Jonas proposed limited camera locations, short data retention and independent access rules",outcome:"the building improved entrance security while protecting private daily activity",insight:"the double edge of technology requires benefits and risks to be designed together",evidence:"The approved plan covered entrances but excluded corridors facing apartment doors",essay:"Balancing Security and Privacy"}
 ]
}
];

export const generatedPapers=unitPlans.flatMap(buildUnitPapers);
